### ISSUE TITLE
Deleting Values from session doesn't work, when no data is left.

### ISSUE THREAD

**Issue by mattrmiller** [phalcon/incubator#193]
I found this when setting flash messages and they were the only data in the session. The flash messages would stay over and over again. This is because the class does not allow all data/variables to be removed, as you are checking data for empty.

In Phalcon\Session\Adapter\Database.php,

``` php
public function write($sessionId, $data)
    {
        if ($this->isDestroyed || empty($data)) {
            return false;
        }
```

should be...

``` php
public function write($sessionId, $data)
    {
        if ($this->isDestroyed) {
            return false;
        }
```

So that data variables can be deleted, and written back to the session/db.

**Comment by noobiwan** [comment]
I can confirm this behavior, how are you supposed to clean the session if you can write empty data?

**Comment by noobiwan** [comment]
Check my patch #517
