### ISSUE TITLE
Translate Gettext - Already in Phalcon 1.3.2

### ISSUE THREAD

**Issue by marek1989** [phalcon/incubator#200]
The \Phalcon\Translate\Adapter\Gettext class is already in Phalcon 1.3.2, but with a bit different configuration like e.g. defaultDomain. Could all options be moved to Phalcon and then this be renamed or removed and documented on Phalcon? This is causing a conflict, as application is taking by default class from Phalcon.

**Comment by Green-Cat** [comment]
@sergeyklay Fixed in 2.0.x
