### ISSUE TITLE
Translate Gettext method names are too general for xgettext

### ISSUE THREAD

**Issue by dschissler** [phalcon/incubator#207]
Rather than add specific view format parsers and ballooning out my project dependencies and making it much more difficult to setup I am instead pointing xgettext at the compiled Volt views on the server side and the compiled views in the webpack bundle for the client side.

In general I think that having very generally named methods like "query" is a good thing but in this particular case it makes it much less useful since xgettext would get a very large number of incorrect hits by looking for functions and methods named 'query'.  I propose that it be called something like "translate_query".

I want to name the singular and plural function calls the same in both Javascript and PHP so that the same "--keyword=FUNCTION_NAME" xgettext switches can be used for both languages to minimize setup complexity.

**Comment by Green-Cat** [comment]
The Gettext Adapter is no longer in incubator.
If it is still relevant, please open an issue @ phalcon/cphalcon.
