### ISSUE TITLE
isAllowed in Phalcon\Acl\Adapter\Database not working for postgresql

### ISSUE THREAD

**Issue by lucvht** [phalcon/incubator#221]
Tried to use `Phalcon\Acl\Adapter\Database` with Postgresql which failed on the `isAllowed` function. The SQL `SELECT` statement is not compatible with Postgresql because by default you cannot do math with boolean values. This can be fixed by changing the `ORDER BY` clause:

```sql
ORDER BY (roles_name != '*')::int+(resources_name != '*')::int+(access_name != '*')::int DESC
```

but I assume this will break MySQL/SQLite ?

**Comment by sergeyklay** [comment]
Can you please test now?

**Comment by aldev-web** [comment]
Hi,

Problem already exist. Fix of lucvht works perfectly. Can you apply ?

**Comment by adam-rocska** [comment]
@lucvht I see, that there is a related PR that's merged. Is this issue closable?
