### ISSUE TITLE
 SQLSTATE[HY093]: Invalid parameter number 

### ISSUE THREAD

**Issue by cullsin** [phalcon/incubator#238]
Hi, 

I have upgrade the incubator plugin with http://invo.phalconphp.com/ project. 

I have upgraded the DB cache in services. php and I have got " SQLSTATE[HY093]: Invalid parameter number" Exception for all the queries . 

``` php
$di->set('db', function() use ($config) {

    $connection = new \Phalcon\Db\Adapter\Cacheable\Mysql(array(
        "host" => $config->database->host,
        "username" => $config->database->username,
        "password" => $config->database->password,
        "dbname" => $config->database->name,
        "options" => array(
            PDO::ATTR_EMULATE_PREPARES => false
        )
    ));

    $frontCache = new \Phalcon\Cache\Frontend\Data(array(
        "lifetime" => 2592000
    ));

    //File backend settings
    $connection->setCache(new \Phalcon\Cache\Backend\File($frontCache, array(
        "cacheDir" => APP_PATH . $config->application->dbCacheDir,
    )));

    return $connection;
});
```

Please let me know If I am missing anything .

**Comment by sergeyklay** [comment]
@cullsin Can u please test on Phalcon 2.0.1 ?

**Comment by cullsin** [comment]
Hi, 

Thanks. I lost the context and I am sure I test it with Phalcon 2.0.1 

Raja K

**Comment by sergeyklay** [comment]
@cullsin Hmm, currently in Phalcon 2.0.1 issue is still exists?

**Comment by cullsin** [comment]
Hi, 

Sorry I will test it and let you know , I guess I made it miscommunication

Raja K

**Comment by TrogWarZ** [comment]
Have same issue.

In services:
```php
$di->setShared('db', function () {
    $db    = new \Phalcon\Db\Adapter\Cacheable\Mysql([
        'adapter'  => 'Mysql',
        'host'     => 'localhost',
        'username' => 'foobar_user',
        'password' => 'foobar_pass',
        'dbname'   => 'foobar_db',
        'options'  => [
            \PDO::ATTR_DEFAULT_FETCH_MODE => PDO::FETCH_OBJ,
            \PDO::MYSQL_ATTR_INIT_COMMAND => 'SET NAMES utf8mb4; SET time_zone = UTC;',
            \PDO::ATTR_EMULATE_PREPARES     => false,
        ],
    ]);
    $front = new \Phalcon\Cache\Frontend\Data();
    $db->setCache(new \Phalcon\Cache\Backend\File($front, [
        'cacheDir' => dirname(dirname(__FILE__)) . '/cache/db/',
    ]));

    return $db;
});
```

In controller:
```php
var_dump($this->db->tableExists('foobar_db', 'foobar_table')); // null
```

I get an error:
```Notice: Cannot use a scalar value as an array in /path/to/project/vendor/phalcon/incubator/Library/Phalcon/Db/Adapter/Cacheable/Mysql.php on line 125```

If i switch to \Phalcon\Db\Adapter\Pdo\Mysql then i see no errors and "1" in output.

PHP 5.6.8
Phalcon 1.3.5

With phalcon 2.0.2 i get another error:
```Fatal error: Declaration of Phalcon\Db\Adapter\Cacheable\Mysql::__construct() must be compatible with Phalcon\Db\AdapterInterface::__construct(array $descriptor) in /path/to/project/vendor/phalcon/incubator/Library/Phalcon/Db/Adapter/Cacheable/Mysql.php on line 0```

**Comment by TrogWarZ** [comment]
Also, with Cacheable adapter i get an "Invalid parameter number" exception for code like this:

```php
$users = Users::find([
    'conditions' => 'foo = :foo: AND bar = :bar: AND gsom = :foo:',
    'bind => [
        'foo' => 42,
        'bar' => 'yo',
    ],
]);
```

Notice that in condition we have "foo" parameter repeated more than once. With default Phalcon adapter this works good. Issue may broke some code.

**Comment by sergeysviridenko** [comment]
@cullsin could you test it on Phalcon 3, please?

**Comment by omnispex** [comment]
I have the same issue tested on latest Phalcon version (3.3)

**Comment by sergeyklay** [comment]
@omnispex Could you please provide a minimal script to reproduce?

**Comment by omnispex** [comment]
Hello Serghei

Sorry for the late reply!
But I’ve created a very small sample app that illustrates my problem.
It worked fine under Phalcon 3.2 but not under the 3.3 version.
The MySql cache class can be found in the helpers folder:

1. Setup a db and run the dump.sql file in schema folder
2. Set proper config vars in app/config settings
3. Set proper permission for app/cache and it’s subfolders.

You can clone  it from my git repository here:

https://github.com/omnispex/phalcondemo.git


Hopefully it will help you to reproduce my problem and hopefully you can trace the problem.

Thanks,

Eric Holtkamp

**Comment by sergeysviridenko** [comment]
@omnispex issue `SQLSTATE[HY093]: Invalid parameter number` appears when your params aren't defined.
Could you try to use like this?
```
$newarticles=$this->modelsManager->createBuilder()
            ->columns(array('Articles.id','Articles.listtitle','Articles.listdescription','Articles.filename','Articles.adddate','Articles.modifydate','Articles.publishdate','Articles.expiredate','Users.username','Users.realname','Images.path','Images.thumbnail'))
            ->from('Articles')
            ->innerJoin('Categoryarticles','Articles.id = Categoryarticles.articleid')
            ->innerJoin('Categories','Categoryarticles.categoryid = Categories.id')
            ->innerJoin('Users','Articles.publishid=Users.id')
            ->leftJoin('Images','Articles.iconid=Images.id')
            ->where('Articles.languagekey=:languagekey:',array('languagekey' => $this->languagekey()))
            ->andWhere('Articles.trash=:trash:',array('trash' => 'no'))
            ->andWhere('Articles.publishdate BETWEEN :startdate: AND :enddate:',array('startdate' => date("Y-m-d",time()-86400*90),'enddate' => date('Y-m-d')))
            ->andWhere('Articles.expiredate>:date:',array('date' => date('Y-m-d')))
            ->andWhere('Categories.languagekey=:languagekey2:',array('languagekey2' => $this->languagekey()))
            ->andWhere('Categories.trash=:trash2:',array('trash2' => 'no'))
            ->andWhere('Users.languagekey=:languagekey3:',array('languagekey3' => $this->languagekey()))
            ->andWhere('Users.trash=:trash3:',array('trash3' => 'no'))
            ->orderBy('Articles.publishdate DESC')
            ->groupBy(array('Articles.id'))
            ->limit(10)
            ->getQuery()
            ->execute()
        ;
```
Your error has to disappear.

**Comment by omnispex** [comment]
Thanks, The error disappeared, but now, I have a **Cache must be started first** error.
Normally this occurs when you've added something like an echo, var_dump, etc before the cache started, but nothing of that is in my code.

**Comment by sergeysviridenko** [comment]
@omnispex you should start your session. This isn't a bug.
