### ISSUE TITLE
https://github.com/phalcon/incubator/blob/v1.3.4/composer.json

### ISSUE THREAD

**Issue by stanislav-web** [phalcon/incubator#262]
ext-phalcon 1.2.4 ? Oo? Cant install , need v1.3.4. dev-master dont resolve the problem

**Comment by sergeyklay** [comment]
The minimum required version. What exactly issue?

**Comment by stanislav-web** [comment]
А, понял... не в этом проблема... Фалькон установлен, но в консоли не виден как расширение
```php
php -m

...
mysqli
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
redis
....
```
composer парсит расширения и подбирает пакеты. 
Фалькон установлен 1.3.4 и прекрасно работает, phpinfo() показывает что стоит.. Странно

**Comment by sergeyklay** [comment]
@stanislav-web  привет

Конкретно в твоём выводе `php -m`, который ты показал выше, нет `phalcon`. 
Можешь в консоли вывести вот это?
```sh
php -r "echo \Phalcon\Version::get();" 
```

**Comment by stanislav-web** [comment]
Да , есть там все, пишу же на нем. Только нет в консоли.. Я исправил, при компиляции расширения, я не поставил символическую ссылку в каталог /etc/php5/cli/conf.d/phalcon.ini .. он по умолчанию стоит в /etc/php5/mods-available/phalcon.ini ... Поэтому в консоли его не видно как расширение

**Comment by sergeyklay** [comment]
Композер ищет расширения в cli режиме
