### ISSUE TITLE
Phalcon/Session/Adapter/Database.php - First Time Login

### ISSUE THREAD

**Issue by cullsin** [phalcon/incubator#264]
Hi, 

Seems like Session handling through Database is not working for first time login . 

I am doing following in session controller, 
$this->session->set("name", "raja");
$this->response->redirect("index");

I am doing following in Index controller, 

$name = $this->session->get("name");

$name is empty for the first time, But when I check the table "session_data", data exists in the table. 

Is it because of  Insert and Select happens at same time ? 

Please suggest me on this .

Thanks,
Raja K

**Comment by ovr** [comment]
$this->session->start() ?

**Comment by cullsin** [comment]
Session Start is in the app services file .

**Comment by cullsin** [comment]
Hi, 

Any update on this ?

Raja K

**Comment by cullsin** [comment]
Hi,

Any update on this ?

Raja K

**Comment by cullsin** [comment]
Thanks, I saw the code update and it's working great
