### ISSUE TITLE
Phalcon\Session\Adapter\Database missing session_register_shutdown()

### ISSUE THREAD

**Issue by ikas** [phalcon/incubator#266]
Phalcon\Session\Adapter\Database missing session_register_shutdown() call in constructor. 

Using the database adapter, if a PHP fatal error occurs and the method stated above is not called, there is a segmentation fault in Apache (I suspect because of Phalcon), and the fatal error message is not displayed.

**Comment by sergeyklay** [comment]
So, what do you suggest?

**Comment by ikas** [comment]
Literally what I said, add 'session_register_shutdown()' to the constructor.

http://php.net/manual/en/function.session-set-save-handler.php

Above is the link to the php manual. In that page, there is a section warning about this exact issue.

**Comment by ikas** [comment]
"When using objects as session save handlers, it is important to register the shutdown function with PHP to avoid unexpected side-effects from the way PHP internally destroys objects on shutdown and may prevent the write and close from being called. Typically you should register 'session_write_close' using the register_shutdown_function() function." 

From the link i put above.

**Comment by sergeyklay** [comment]
Okay, do PR please
