### ISSUE TITLE
Phalcon - Config, Service and Loader - Driven from Database

### ISSUE THREAD

**Issue by cullsin** [phalcon/incubator#270]
Hi, 

I would like to convert Config, Service and Loader php files into a Database / table driven object. 

Can you suggest me how do i do that ? I am stuck at Services configurations as I am unable to bring 

the framework.  

Please suggest me on this.

**Comment by endeveit** [comment]
Hi.
Could you please provide example?
I cannot imagine situation when Service and Loader are stored in database.

**Comment by cullsin** [comment]
Hi, 

I want to configure different Service ( enable / Disable ) and Loader, Config.ini  in the database for multiple sites .

I didn't mean that I am going to store Services.php and Loader.php in database.

So, from the admin website, I can generate $di ( dependency Injection object ) for different site and 

put it in the memcache system. 

Please let me know your comments on the same .

Raja K

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests.

For questions regarding the usage of the framework or support requests please visit the official [forums](http://forum.phalconphp.com/).
