### ISSUE TITLE
Twig won't work with the tag functions?

### ISSUE THREAD

**Issue by MCGamer20000** [phalcon/incubator#280]
Okay, I can NOT figure out how to do the Volt equivalent of `{{ textField('username', 'size': 30) }}` in Twig. I've been stuck on this problem for an hour. Can someone please confirm that I'm not just going crazy?

**Comment by MCGamer20000** [comment]
`{{ textField({0: 'username', 'size': 30}) }}`
Okay, surely that can't be the intended syntax... It works, but that just looks like a workaround to me. Is there any better syntax to use?

**Comment by endeveit** [comment]
Unfortunately no.
This is a feature of phalcon.
