### ISSUE TITLE
Phalcon\Queue\Beanstalk\Extended fault readme document.

### ISSUE THREAD

**Issue by lixiphp** [phalcon/incubator#285]
````
$beanstalk->addWorker('processVideo', function (Job $job) {
    $videoId = $job->getBody();
});

$beanstalk->addWorker('deleteVideo', function (Job $job) {
    unlink('/var/www/data/' . $videoId . '.flv');
});
````

do you mean add Worker or add Function ?

````
$tubes = array_keys($this->workers);

        do {
            if (!empty($this->workers)) {
                $tube = $tubes[array_rand($tubes)];
````

why rand the worker, it makes the fault function called.

can you fixed the document? Thanks a lot.

**Comment by endeveit** [comment]
1. «worker» is any valid callable callback.
E.g.
```php
// closure
$beanstalk->addWorker('processVideo', function (Job $job) {});

// simple callback
$beanstalk->addWorker('processVideo', 'my_callback_function');

// use simple callback
$beanstalk->addWorker('processVideo', 'my_callback_function');

// static class method call
$beanstalk->addWorker('processVideo', array('MyClass', 'myCallbackMethod')); 

// object method call
$obj = new MyClass();
$beanstalk->addWorker('processVideo', array($obj, 'myCallbackMethod')));

// static class method call
$beanstalk->addWorker('processVideo', 'MyClass::myCallbackMethod'); 
```

2. Callbacks are attached to tubes:
```php
// will call random of ['my_process_video_0', 'my_process_video_1']
$beanstalk->addWorker('processVideo', 'my_process_video_0');
$beanstalk->addWorker('processVideo', 'my_process_video_1');

// will call random of ['my_process_image_0', 'my_process_image_1']
$beanstalk->addWorker('processImage', 'my_process_image_0');
$beanstalk->addWorker('processImage', 'my_process_image_1');
```

Where is mistakes?

**Comment by lixiphp** [comment]
controller.php
````
/**
     * Deletes the video.
     */
    public function deleteVideoAction()
    {
        // Connect to the queue
        $beanstalk = new BeanstalkExtended(array(
            'host'   => '192.168.0.21',
            'prefix' => 'project-name',
        ));

        // Send the command to physical unlink to the queue
        $beanstalk->putInTube('processVideo', 4871);
    }
````
worker.php
````
$beanstalk->addWorker('processVideo', function (Job $job) {
    $videoId = $job->getBody();
});

$beanstalk->addWorker('deleteVideo', function (Job $job) {
    unlink('/var/www/data/' . $videoId . '.flv');
});
````
the worker random run deleteVideo or processVideo worker for processVideo tube(task), because random the workers to run the task. is it right?

**Comment by endeveit** [comment]
Nope.
I'm sorry I've provided incorrect example.
It should be
```php
$beanstalk->addWorker('processVideo', 'my_process_video_0');
$beanstalk->addWorker('processImage', 'my_process_image_0');

// start infinite loop and call random of workers
// «my_process_video_0» and «my_process_image_0» for
// tubes «processVideo» and «processImage» accordingly 
$beanstalk->doWork()
```

**Comment by sergeyklay** [comment]
@lixiphp issue can be closed?

**Comment by lixiphp** [comment]
@sergeyklay Thank your response, but I still test the worker working incorrectly, the processVideo job run in processImage worker sometime, anybody meet the same situation?

**Comment by endeveit** [comment]
@lixiphp this is correct.
One worker can process different jobs.

**Comment by endeveit** [comment]
If you want to processVideo and processImage in different threads, you should split it to different files.

process-video.php:
```php
<?php
$beanstalk->addWorker('processVideo', 'my_process_video_0');
$beanstalk->doWork();
```

process-image.php
```php
<?php
$beanstalk->addWorker('processImage', 'my_process_image_0');
$beanstalk->doWork();
```

**Comment by lixiphp** [comment]
@endeveit yes, I do it like your suggestion in different php scripts, but in a same php script, the worker not run with the same name worker as I specify. is it right?

**Comment by endeveit** [comment]
What did yo mean?
Could you please provide example.

**Comment by KristijanBenkovic** [comment]
@endeveit 
referring to documentation processVideo and deleteVideo workers are in the same file (thread). So controller's uploadVideoAction may invoke deleteVideo and Vice versa.

**Comment by endeveit** [comment]
Each worker will work with his tube. (https://github.com/phalcon/incubator/blame/master/Library/Phalcon/Queue/Beanstalk/README.md#L30 and https://github.com/phalcon/incubator/blame/master/Library/Phalcon/Queue/Beanstalk/README.md#L46)
How action uploadVideoAction can invoke tube "deleteVideo"?

**Comment by KristijanBenkovic** [comment]
@endeveit 

I have tested with \Phalcon\CLI\Task: 

```php
use Phalcon\Queue\Beanstalk\Job;

class BeanstalkWorkerTask extends \Phalcon\CLI\Task
{

    public function startAction() 
    {
    	$beanstalk = $this->getDI()->get(AppServices::BEANSTALKD_EXTENDED);

		$beanstalk->addWorker('sendEmailConfirmation', function (Job $job) {

			echo "right method";
			echo "\n\t";

			print_r($job->getBody());
			echo "\n\t";

			exit(0);

		});

		$beanstalk->addWorker('foo', function (Job $job)  {

			echo "wrong method";
			echo "\n\t";

			print_r($job->getBody());
			echo "\n\t";

			exit(0);
		});

		$beanstalk->doWork();

    }
}
```
and \Phalcon\Mvc\User\Plugin:

```php
class TestService extends \Phalcon\Mvc\User\Plugin 
{

     public function Test() {

        $bs = $this->di->get(AppServices::BEANSTALKD_EXTENDED);
        
        $bs->putInTube('sendEmailConfirmation',1);
        $bs->putInTube('sendEmailConfirmation',2);
        $bs->putInTube('sendEmailConfirmation',3);
        $bs->putInTube('sendEmailConfirmation',4);
        $bs->putInTube('sendEmailConfirmation',5);
     }

}
```

and the output is 
```
    right method
	1
	wrong method
	2
	wrong method
	3
	wrong method
	4
	right method
	5
```
So if I put job in sendEmailConfirmation tube it random pick a tube. As you said [above](https://github.com/phalcon/incubator/issues/285#issuecomment-98565854) this is expected behaviour. So what is the point of multiple tubes?

**Comment by endeveit** [comment]
@KristijanBenkovic now I see!
Thank you!
This is a bug, I'll try to fix it as soon as i can

**Comment by lixiphp** [comment]
@endeveit  I have fixed the error example code, can I pull request the code to you.

**Comment by endeveit** [comment]
@lixiphp sure you can

**Comment by lixiphp** [comment]
@endeveit add a pull request in branch "lixiphp-patch-issue-285", please review.

**Comment by endeveit** [comment]
Could you please make PR to phalcon:2.0.x?

**Comment by lixiphp** [comment]
@endeveit OK

**Comment by lixiphp** [comment]
@endeveit I have make a new PR to phalcon:2.0.x branch.

**Comment by endeveit** [comment]
@lixiphp I don't see it in list of PR here https://github.com/phalcon/incubator/pulls

**Comment by lixiphp** [comment]
@endeveit https://github.com/phalcon/incubator/pull/406 can you see it?

**Comment by lixiphp** [comment]
Fixed. checkout the lastest README example in 2.0.x branch.
