### ISSUE TITLE
Phalcon Session - inactive Sessions

### ISSUE THREAD

**Issue by cullsin** [phalcon/incubator#294]
Hi, 

I would like to know how do I remove the unused Sessions from the session_data. This happens when the user close the browser. Is there any way to get the list of Inactive Sessions from the database and I can trigger the event. 

I could also trigger the event for browser close, But let me know your suggestion .

Raja K

**Comment by yergo** [comment]
Assuming you use Adapter/Database, `gc` method should do this for you if you have properly configured `session.gc_maxlifetime`. If not, there may be an issue.
