### ISSUE TITLE
[2.0.x] View\Engine compatlibity

### ISSUE THREAD

**Issue by CawaKharkov** [phalcon/incubator#322]
**\Phalcon\Mvc\View\Engine\Twig::construct()** must be compatible with **\Phalcon\Mvc\View\EngineInterface::__construct($view, \Phalcon\DiInterface $dependencyInjector = null)**

\Phalcon\Mvc\View\Engine\Twig::__construct:
```php
 /**
     * {@inheritdoc}
     *
     * @param \Phalcon\Mvc\ViewInterface $view
     * @param \Phalcon\DiInterface       $dependencyInjector
     */
    public function __construct($view, \Phalcon\DiInterface $dependencyInjector = null)
    {
        $loader     = new \Twig_Loader_Filesystem($view->getViewsDir());
        $this->twig = new Twig\Environment($dependencyInjector, $loader);

        $this->twig->addExtension(new Twig\CoreExtension());
        $this->registryFunctions($view, $dependencyInjector);

        parent::__construct($view, $dependencyInjector);
    }
```

**Comment by sergeyklay** [comment]
This valid only for Phalcon 2.x

**Comment by CawaKharkov** [comment]
Yes, I know. But there's no branch for 2.0  yet.

**Comment by sergeyklay** [comment]
Well, we need 2.0.x branch

**Comment by sergeyklay** [comment]
@CawaKharkov Can u please do PR into 2.0.x please?

**Comment by CawaKharkov** [comment]
Yes, I will, in a few hours I think.

**Comment by CawaKharkov** [comment]
#323 PR

**Comment by henrmota** [comment]
use Phalcon\Mvc\ViewBaseInterface  ViewBaseInterface $view in construct twig

**Comment by endeveit** [comment]
@henrmota unfortunately Phalcon\Mvc\ViewBaseInterface exists only in master branch it doesn't exists in v2.0.0

**Comment by endeveit** [comment]
Done in #343
