### ISSUE TITLE
no Memcache Adapter on 2.0.x branch

### ISSUE THREAD

**Issue by hardlick** [phalcon/incubator#326]
Hi, in 2.0.x branch no Memcache Adapter why?

**Comment by sergeyklay** [comment]
Adapter for ... ?

**Comment by hardlick** [comment]
Memcached Adapter, incubator no more extend for memcached adapter on 2.0.x ?

**Comment by sergeyklay** [comment]
Adapter for Session, Cache, Annotations, etc.? What of adapter?

**Comment by hardlick** [comment]
ohhh, for Session...

**Comment by sergeyklay** [comment]
Incubator 2.0.x branch for Phalcon 2.x. Memcache session adapter for Phalcon 2.x is available from Phalcon 2.x out of box.

**Comment by hardlick** [comment]
oh Ok, this is correct...ok! thanks!
