### ISSUE TITLE
Frontend Cache: Msgpack how to delete cache contents?

### ISSUE THREAD

**Issue by hardlick** [phalcon/incubator#335]
i defined my view Cache:

    $di->set('viewCache', function() {

    //Create a Data frontend and set a default lifetime to 1 hour
    $frontend = new Phalcon\Cache\Frontend\Msgpack(array(
        'lifetime' => 3600
    ));

    $cache = new Phalcon\Cache\Backend\Memory($frontend);

    return $cache;
});     

Now, how i can use? on my volt templates to cache?, and how to destroy all cache content ?

**Comment by sergeyklay** [comment]
For questions regarding the usage of the framework or support requests please visit the [official forums](http://forum.phalconphp.com/).

**Comment by hardlick** [comment]
All right, you're right!
