### ISSUE TITLE
Behavior::notify Declaration not compatible with Phalcon 2.0.x

### ISSUE THREAD

**Issue by thxer92** [phalcon/incubator#345]
Hi,

I got this error:
Strict standards: Declaration of Phalcon\Mvc\Model\Behavior\Blameable::notify() should be compatible with Phalcon\Mvc\Model\Behavior::notify($type, Phalcon\Mvc\ModelInterface $model)

You have to add \Phalcon\Mvc\ModelInterface typehint to blameable behavior notify function.

**Comment by sergeyklay** [comment]
Fixed in 2.0.x
