### ISSUE TITLE
Php Redis Backend Cache Documentation

### ISSUE THREAD

**Issue by luhuiya** [phalcon/incubator#349]
I am having issue of connecting redis using phalcon

i am using the code in the incubator readme
```php

$di->set('cache', function() {

	//Connect to redis
	$redis = new Redis();
	$redis->connect('127.0.0.1', 6379);

	//Create a Data frontend and set a default lifetime to 1 hour
	$frontend = new Phalcon\Cache\Frontend\Data(array(
	    'lifetime' => 3600
	));

	//Create the cache passing the connection
	$cache = new Phalcon\Cache\Backend\Redis($frontend, array(
		'redis' => $redis
	));

	return $cache;
});

```

it always wanted to connect to localhost
but i solved it by changed it to

 $cache = new Phalcon\Cache\Backend\Redis($frontend, array(
                'redis' => $redis,
                'host' => $app_config->redis->host,
                'port' => $app_config->redis->port,
        ));

**Comment by endeveit** [comment]
@luhuiya you're connecting to 127.0.0.1, don't you?
Change "$redis->connect('127.0.0.1', 6379);" to "$redis->connect($app_config->redis->host, $app_config->redis->port);" and everything will work as you expect.

**Comment by endeveit** [comment]
@luhuiya BTW what Phalcon version do you use?
In v2.0 redis backend was moved to core from incubator

**Comment by luhuiya** [comment]
i am using version 2.0 so not incubator

it is the sample, mine was like this, i am able to solve the problem just worry it happens to others

/**
 * cache using redis
 */
$di->set('cache', function() use ($app_config) {

	//Connect to redis
	$redis = new Redis();
	$redis->connect($app_config->redis->host, $app_config->redis->port);

	//Create a Data frontend and set a default lifetime to 1 hour
	$frontend = new Phalcon\Cache\Frontend\Data(array(
	    'lifetime' => 3600
	));

	//Create the cache passing the connection

    //Create the cache passing the connection
    $cache = new Phalcon\Cache\Backend\Redis($frontend, array(
        'redis' => $redis
    ));

	return $cache;
});

**Comment by endeveit** [comment]
@luhuiya thank you.
I remove obsolete docs in v2.0 branch

**Comment by Surt** [comment]
I can't connect using this way with 2.0.10, and I can't see any clue on cphalcon indicating it could be done:

```php 
 //Create the cache passing the connection
    $cache = new Phalcon\Cache\Backend\Redis($frontend, array(
        'redis' => $redis
    ));
```

**Comment by sergeyklay** [comment]
@Surt Create please separated issue
