### ISSUE TITLE
Incubator Files are not Loading

### ISSUE THREAD

**Issue by JellyM** [phalcon/incubator#351]
I'm having issue with loading incubator files into my project.

I downloaded files from GitHub's website (the download zip button).

I'm using ```Phalcon\Loader``` to register the namespace for Phalcon as it's stated in the README.md
I can clearly see registered namespace via ```spl_autoload_functions()```
```["Phalcon"]=>"/var/www/html/project/apps/vendor/phalcon/incubator/" ```

And full path of the class file is ```/var/www/html/project/apps/vendor/phalcon/incubator/Utils/Slug.php```

Unfortunately I keep getting class not found error when I try to use incubator classes;

```PHP
namespace AppName\Models

use Phalcon\Utils\Slug;

class MyModel 
{
    public function myMethod()
    {
        $slug = Slug::generate("testing slug");
        var_dump($slug);
    }
}
```

I get class not found error; ```PHP Fatal error:  Class 'Phalcon\\Utils\\Slug' not found```

Why the registered namespaces are not working?
I'm using Phalcon 2.0.0

**Comment by ilgityildirim** [comment]
I wish you would mention in SOF about downloading via zip button as well.
Check your file and folder permissions and make sure they are accessible.

**Comment by JellyM** [comment]
@ilgityildirim Thank you! I just copied and pasted the files and folders. I didn't think about checking file permissions.
