### ISSUE TITLE
\Acl\Adapter\Database with caching feature

### ISSUE THREAD

**Issue by One-art** [phalcon/incubator#371]
Hello. 
I want to use Database adapter to acl but with caching.
And possibility to use memory and database adapter together?
Any suggestions about right way appreciated

**Comment by Green-Cat** [comment]
Memory is not a caching mechanism (It is loaded into memory for a request, but does not stay there, that's not possible in php).

**Comment by andresgutierrez** [comment]
You can cache the results in APC/Redis/Memcached which is shared memory

**Comment by Jurigag** [comment]
@One-art also most of databases already have built-in query based cache result. If table change then query is invalided. At leasy mysql have such a feature.
