### ISSUE TITLE
mailer can't find view.volt

### ISSUE THREAD

**Issue by stefanchiriac** [phalcon/incubator#379]
Hello,

Phalcon\Mvc\View\Exception: View '/home/xxx/www/xxx/themes/default/emails/confirmation' was not found in the views directory
```/home/xxx/www/xxx/app/vendor/phalcon/incubator/Library/Phalcon/Mailer/Manager.php (314)```

on config I added
```'viewsDir' => '/home/xxx/www/xxx/themes/default/emails/'```

and when I call the view

    $this->getDI()->getShared('mail')->createMessageFromView('confirmation', $params)
        ->to($this->user->getEmail())
        ->subject('Confirm your email')
        ->send();

volt is defined and working properly with the rest of volt pages, but not with mailer
I tried with phtml and is working but only using smtp; with mail is not sending anything.
There is no volt support or is a bug?

Thanks

**Comment by endeveit** [comment]
Have you tried to use «confirmation.volt» instead of «confirmation» in createMessageFromView method?

**Comment by stefanchiriac** [comment]
yes. I tried with and without .volt extension. Same error.

**Comment by KorsaR-ZN** [comment]
@stefanchiriac This component is no longer maintained.
Please use https://github.com/phalcon-ext/mailer

**Comment by stefanchiriac** [comment]
Thanks
I see that overall, incubator is not maintained too much and is quite sad. Phalcon is missing quite a few things and incubator is supposed to be a good all in one solution for these gaps.

**Comment by KorsaR-ZN** [comment]
I believe that incubator should be divided into smaller components. :)
