### ISSUE TITLE
Eager Loading with Empty Resultset throw "InvalidArgumentException"

### ISSUE THREAD

**Issue by Wayne-Wen** [phalcon/incubator#380]
@stibiumz I got "Expected value of `subject` is either a ModelInterface object, a Simple object or an array of ModelInterface objects" when calling \Phalcon\Mvc\Model\EagerLoading\Loader::fromResultset($items,"RelationA","RelationB");
In my case, $item is an instance of "Simple" resultset with none records in it. Because there is none records in database according to my search query.

I think Eager loading should handle the "Empty" model (including empty parent, ref: https://github.com/stibiumz/phalcon.eager-loading/issues/4 ) more carefully.

**Comment by stibiumz** [comment]
Hi,

you're right, I'll change that this week and submit changes to this repository too.

Thanks

**Comment by Wayne-Wen** [comment]
@stibiumz I just found an bug in "EagerLoadingTrait.php" line 54; When $ret is a empty result set, the $ret[0] will throw exception. Please check this as well.
