### ISSUE TITLE
Phalcon/Translate/Adapter/Database.php function "exists"

### ISSUE THREAD

**Issue by Xerton** [phalcon/incubator#399]
Hi,

I use Database translation and I try to use "exists" function.

    public static function getTranslation()
    {
        return new \Phalcon\Translate\Adapter\Database( [ 'db' => \Phalcon\DI\FactoryDefault::getDefault()->getShared('db'), 'table' => 'translations', 'language' => Utils::getLanguage() ]);
    }

    $t = self::getTranslation()->exists('foo');

result : 

    SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '0' at line 1

Database.php line 95 :

    "SELECT COUNT(*) FROM " . $options['table'] . " WHERE key_name = ?0",

I change to :

    "SELECT COUNT(*) FROM " . $options['table'] . " WHERE key_name = ?",

And it works.

**Comment by sergeyklay** [comment]
Fixed in `2.0.10`
