### ISSUE TITLE
[NFR] NestedSet behaviour - ability to customize database service name in DI 

### ISSUE THREAD

**Issue by temuri416** [phalcon/incubator#424]
Hi,

https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Behavior/NestedSet.php#L790

In my app I have a different way of determining active DB handler. Maybe we should use constructor to set custom DB connection?

```php
$this->addBehavior(new NestedSetBehavior([
    'db' => $db,
]);
```

Thanks!

**Comment by sergeyklay** [comment]
@temuri416 
Hello
Great idea. Can you please create PR to 2.0.x branch?

**Comment by temuri416** [comment]
PR's ready for your review.

**Comment by temuri416** [comment]
Thanks!

What's the plan - when will 2.0.x be merged into master?

**Comment by sergeyklay** [comment]
After releasing Phalcon 2.0.8
