### ISSUE TITLE
Cannot using "duncan3dc/fork-helper"!!!

### ISSUE THREAD

**Issue by Wayne-Wen** [phalcon/incubator#432]
When we update incubator to 2.0.8 via composer, we got following error:

      duncan3dc/fork-helper 1.0.1 requires ext-pcntl * -> the requested PHP extension pcntl is missing   from your system.

I have checked the "pcntl" extension via php.net and notice that this extension is not available on Windows platforms. However, our whole team is using Windows. Therefore, we have to downgrade incubator's version to 2.0.7. Does it mean we have to change our OS to Linux??? Could anyone help?

**Comment by endeveit** [comment]
@Wayne-Wen please check with the latest version

**Comment by Wayne-Wen** [comment]
@endeveit Thank you. I'm just considering How can we use "Phalcon/Queue/Beanstalk/Extended" without "fork". Is there any alternative package to replace "duncan3dc/fork-helper"?

**Comment by endeveit** [comment]
@Wayne-Wen I don't know the proper way to fork process on Windows.
Without fork the whole idea of Phalcon\Queue\Beanstalk\Extended makes no sense.
