### ISSUE TITLE
Decimal Validator Is Not Working

### ISSUE THREAD

**Issue by ilgityildirim** [phalcon/incubator#435]
I'm using Phalcon 2.0.7, I wanted to use Decimal validator and I had the following error (grabbed it from Apache's error log)

    PHP Fatal error:  Declaration of Phalcon\\Mvc\\Model\\Validator\\Decimal::validate() must be compatible with Phalcon\\Mvc\\Model\\ValidatorInterface::validate(Phalcon\\Mvc\\EntityInterface $record) in /var/www/html/phalcon/project/script/app/library/Phalcon/Mvc/Model/Validator/Decimal.php on line 43

Just wanted to drop this one here.

**Comment by endeveit** [comment]
@ilgityildirim please check with the latest version of incubator
