### ISSUE TITLE
phpunit setUp has changed and it has not been noticed

### ISSUE THREAD

**Issue by pablomoreno61** [phalcon/incubator#510]
In the last update of phalcon incubator, the method setUp from Phalcon\Test\UnitTestCase has been changed:

Before the changes, the interface was like:

```
protected function setUp(DiInterface $di = null, Config $config = null)
```

while now it is as follows:

```
protected function setUp()
```

This means that your documentation is outdated (https://docs.phalconphp.com/en/latest/reference/unit-testing.html).

Using the old incubator you did:

```
parent::setUp($yourDi, $yourConfig);
```

While now, this doesn't works and you have to do:

```
parent::setUp();

$this->setDI($yourDi);
$this->setConfig($yourConfig);
```

**Comment by sergeyklay** [comment]
@pablomoreno61 
1. Pull request: https://github.com/phalcon/incubator/pull/467
2. Documentation: https://github.com/SidRoberts/phalcon-docs/commit/801e1a9bfe5e8253a485afcfaeccc25bcd08235c

@SidRoberts These changes is not in the production yet?

**Comment by sergeyklay** [comment]
@andresgutierrez Can you please update docs site?
