### ISSUE TITLE
Change from phalcon-ext to phalex

### ISSUE THREAD

**Issue by leocaseiro** [phalcon/incubator#524]
The Library *[phalcon-ext](https://github.com/tmquang6805/phalcon-ext)* is abandoned and no longer maintained. The author suggests using the [tmquang6805/phalex](https://github.com/tmquang6805/phalex) package instead. Should not incubator up to date?

**Comment by sergeyklay** [comment]
`ext-phalcon` not `phalcon-ext` is a virtual package.

> Composer has platform packages, which are virtual packages for things that are installed on the system but are not actually installable by Composer. This includes PHP itself, PHP extensions and some system libraries.

To validate the availability of PHP extensions, all that is needed is to preface its name with **ext-** and add it to the **requre** section of the `composer.json` file.
