### ISSUE TITLE
[FEATURE] Support for ext-mongodb

### ISSUE THREAD

**Issue by MaDKaTZe** [phalcon/incubator#531]
Hello,

are there any plans to support [ext-mongodb](http://pecl.php.net/package/mongodb) as the old *mongo* driver is deprecated and not supported by PHP 7 either. Also it doesn't met up with current version of MongoDB (which is 3.2) as the time of writing.

Thanks

**Comment by Green-Cat** [comment]
There is already an issue on the main project phalcon/cphalcon#11156
