### ISSUE TITLE
[BUG] NestedSet behaviour: moveAsFirst() not working.

### ISSUE THREAD

**Issue by temuri416** [phalcon/incubator#534]
Hi,

I'm following **Tree modification methods** example at:

https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Mvc/Model/Behavior

The following **moveAsFirst()** call does not do anything at all:

```php
$x100=Categories::findFirst(10);
$samsung=Categories::findFirst(7);
$x100->moveAsFirst($samsung);
```
As a result **$x100** remains where it was - under _Mobile Phones -> Audi_. No left or right values are updated anywhere in the table by **moveNode()**.

Thanks

**Comment by sergeyklay** [comment]
Hi @temuri416 I need script to reproduce (including table schema)

**Comment by Zaszczyk** [comment]
I also have this same problem on my own code.
I created such nodes with NestedSetBehavior:
![tree](https://cloud.githubusercontent.com/assets/7737337/13094307/14861c6e-d50a-11e5-987c-c81695b47e62.png)
And I try move PHP as backend's child:
```
$backend= Department::findFirstById(13);
                if(!$backend){
                    throw new ServiceException('...');
                }
$php->moveAsLast($parent);
```
The code executes without any errors, but there are no changes in database. I've also tried with moveAsFirst(). I use NestedSet with `'hasManyRoots' => true`

**Comment by Zaszczyk** [comment]
@sergeyklay Hi, I found You were inspiring with: https://github.com/yiiext/nested-set-behavior so I decided to compare both classes line after line and I found typo here:
https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Behavior/NestedSet.php#L651. It should be:
`$this->rootAttribute => $target->{$this->rootAttribute}`
Just $owner to $target.

After this fix, it works a little more correctly, but not at all. It is needed to comment line 662 (https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Behavior/NestedSet.php#L662): 
`$this->shiftLeftRight($right + 1, $left - $right - 1);`
to correct executions of moveAsFirst and moveAsLast. However I dont know, why this line is incorrect.

I hope my discovery will help You a little :)

**Comment by sergeyklay** [comment]
@temuri416 Can you please check now `2.0. x` branch?

**Comment by sergeyklay** [comment]
@temuri416 Could you please test #552 before I'll merge it

**Comment by temuri416** [comment]
Works as expected on #552:

```php
// Create Root #1.
$root = new Node;
$root->title = 'ROOT A';
$root->saveNode();
$r1 = $root->getId();

// Add "A" as child of root
$node1=new Node;
$node1->title='A';
$node1->appendTo($root);

// Add "B" as last child of root - should be below A
$node2=new Node;
$node2->title='B';
$node2->appendTo($root);

// Add "C" as first child of root - should be above A
$node3=new Node;
$node3->title='C';
$node3->prependTo($root);

// Create Root #2.
$root = new Node;
$root->title = 'ROOT 2';
$root->saveNode();
$r2 = $root->getId();

// Create child of Root #2
$node1=new Node;
$node1->title='2.a';
$node1->prependTo($root);

// Load Root #1.
$root1 = Node::findFirst($r1);

// Load Root #2.
$root2 = Node::findFirst($r2);

// Move Root #2 with its child as first child of Root #2 - above "C".
$root2->moveAsFirst($root1);

// Load 'B'.
$nodeB = Node::findFirst(3);

// Move it as first child of 'ROOT A'.
$nodeB->moveAsFirst($root1);
```

Tree looks as:

```
ROOT A
    B
    ROOT 2
        2.a
    C
    A
```

**Comment by sergeyklay** [comment]
Well morning I'll merge it

**Comment by temuri416** [comment]
Thank you so much.

**Comment by sergeyklay** [comment]
Fixed in `2.0.x`

**Comment by temuri416** [comment]
When will this be merged into master?

**Comment by sergeyklay** [comment]
After Phalcon 2.0.11 release
