### ISSUE TITLE
Undefined index: db in \vendor\phalcon\incubator\Library\Phalcon\Session\Adapter\Database.php on line 111

### ISSUE THREAD

**Issue by denysmakarenko** [phalcon/incubator#539]

**Comment by denysmakarenko** [comment]
I found the reason of this error message.
In Database adapter class on the line 54 you have a string 
unset($options['db'])
After that on the line 68 we call parent class  parent::__construct($options) but as you understand options db is unsetting earlier.
Why you do this?

**Comment by sergeyklay** [comment]
@denysmakarenko Can you please check `2.0.x` branch?

**Comment by denysmakarenko** [comment]
Everything is ok. How I install correct dependeny by composer to my project?

**Comment by sergeyklay** [comment]
* For Phalcon 2.0.x `composer require phalcon/incubator:2.0.x-dev`
* For Phalcon 2.1.x `composer require phalcon/incubator:2.1.x-dev`
