### ISSUE TITLE
Mailer problem

### ISSUE THREAD

**Issue by XartIrok** [phalcon/incubator#541]
error

> Service '\Swift_SmtpTransport' wasn't found in the dependency injection container

section to load

```
        $loader->registerNamespaces(
            array(
                "Phalcon" => APP_PATH.'vendor/phalcon/incubator/Library/Phalcon/'
            )
        );

        $eventsManager = new EventsManager();
        $eventsManager->attach('loader', function ($event, $loader) {
           if ($event->getType() == 'beforeCheckPath') {
               echo $loader->getCheckedPath();
           }
        });

        $loader->setEventsManager($eventsManager);
        $loader->register();

        $di->set('mailer', function () use ($config) {
            return new MailerSend($config->mailer->toArray());
        });
```

i use composer to install, mayby there is wrong

```
{
  "require": {
    "phalcon/incubato": "^2.0"
  },
  "config": {
    "vendor-dir": "vendor"
  }
}
```

**Comment by sergeyklay** [comment]
Composer way:

Use `composer.json` as follows:
```json
{
    "require": {
        "phalcon/incubator": "^2.0"
    }
}
```

then run the composer installer:

```bash
$ php composer.phar install
```

and use something like 
```php
include_once vendor/autoload.php
```

without `$loader->registerNamespaces`

**Comment by XartIrok** [comment]
i must say is strange, but now is working thanks

**Comment by maxttor** [comment]
I have same problem.

I use include_once vendor/autoload.php in bootstrap file but have the problem.

**Comment by maxttor** [comment]
Swift 6.0.0 (2017-05-19) CHANGES:
removed Swift_MailTransport and Swift_Transport_MailTransport

How now I can use driver "mail" ?

**Comment by zeoharlem** [comment]
$helper->getLoginUrl(your_redirect_url, ['email']); 

add the email scope like the above example... this solved the problem for me
