### ISSUE TITLE
Strict Standards notice on Phalcon/Db/Dialect/MysqlExtended.php

### ISSUE THREAD

**Issue by sverdier** [phalcon/incubator#556]
When I use 'dialectClass' => '\Phalcon\Db\Dialect\MysqlExtended'
I have this notice :
Strict Standards: Declaration of Phalcon\Db\Dialect\MysqlExtended::getSqlExpression() should be compatible with Phalcon\Db\Dialect::getSqlExpression(array $expression, $escapeChar = NULL, $bindCounts = NULL) in /vagrant/www/vendor/phalcon/incubator/Library/Phalcon/Db/Dialect/MysqlExtended.php on line 0

**Comment by sergeyklay** [comment]
Could you please provide Phalcon & Incubator versions ?

**Comment by sverdier** [comment]
Phalcon 2.0.9
Incubator 2.0.10

**Comment by sergeyklay** [comment]
Fixed in `2.0.x`
