### ISSUE TITLE
ACL Adapters in 3.0.x

### ISSUE THREAD

**Issue by Jurigag** [phalcon/incubator#558]
How about implementing https://github.com/phalcon/docs/blob/master/en/reference/acl.rst#function-based-access in acl adapters ?

Dont know how exactly it should be working - i guess serializing/unserializing function ? But default serialize/deserialize methods in php cant serialize Closures so we would need to add/implement some library which will allow us such a thing.

There are some code for serializing/deserializing closures in php : http://www.htmlist.com/development/extending-php-5-3-closures-with-serialization-and-reflection/

That would need to implement additional class for ACL Functions i guess to make them serializable(they would be just objects).

@sergeyklay

**Comment by uonick** [comment]
@Jurigag 
https://github.com/phalcon/incubator/commit/0e81371e0db18a98d36b789bc9f19a4ab3be7001

**Comment by Jurigag** [comment]
@uonick 

But it's only making them to work with 2.1.x, not actually implementing behaviour which have Phalcon\Acl\Adapter\Memory:

https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/acl/adapter/memory.zep#L676

**Comment by sergeysviridenko** [comment]
@Jurigag Could you give more information?
`https://github.com/phalcon/docs/blob/master/en/reference/acl.rst#function-based-access` link is bad

**Comment by sergeyklay** [comment]
@sergeysviridenko The new URL is https://docs.phalconphp.com/en/3.2/acl#function-based-access

**Comment by sergeysviridenko** [comment]
@sergeyklay Thank you

**Comment by emiliodeg** [comment]
We can implement to serialize and unserialize closures with [Super Closure](https://github.com/jeremeamia/super_closure)
