### ISSUE TITLE
Http Custom Headers

### ISSUE THREAD

**Issue by diegomurbanos** [phalcon/incubator#575]
Good day 

I'm using Incubator library, specifically the Http/Client. I want to send a POST request with a custom headers, I try with the next code:
```php
$provider = Request::getProvider();
$provider->header->set('Content-Type', 'application/x-www-form-urlencoded');
$provider->header->set('client_id', 'aplicationid');
```

The problem is that this function send the custom header into an array variable call fields. How can I send custom headers outside this array?

Thanks for your answer.

**Comment by sergeyklay** [comment]
Could you please explain a bit more? Which exact result do you expect?

**Comment by diegomurbanos** [comment]
I defined 3 custom headers, Content-Type, client_id and secret_id, but this
custom headers are located in an array call "fields". I need my custom
headers outside from this array.

[image: Imágenes integradas 1]

this is my actual code.

[image: Imágenes integradas 2]

2016-04-25 12:48 GMT-05:00 Serghei Iakovlev <notifications@github.com>:

> Could you please explain a bit more? Which exact result do you expect?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/phalcon/incubator/issues/575#issuecomment-214458122>
>



-- 
Diego Alfonso Prieto Torres
Developer
Tel: (+57 1) 329 7436
Cel: (+57) 315 616 2527
Web: mensajerosurbanos.com <http://www.mensajerosurbanos.com/>

**Comment by phalcondroid** [comment]
$customHeaders = [
     "client_id" => "ex",
     "client_id2" => "ex2"
];

$provider->header->set('Content-Type', 'application/x-www-form-urlencoded');

//outside headers??????
foreach ($customHeader as $key => $value) {
      $provider->header->set($key, $value);
}

//I dont understand :(

**Comment by diegomurbanos** [comment]
Sorry I try to explain better, when I use the function $provider->header->set('application_id', 'appid'); that create my custom header into a variable call "fields", but the API that I'm using dont recognize this variable. Example

With Incubator the header is:

headers => array(
    "field" => array(
        "client_id"=>"xxxx",
        "client_secret"=>"xxxxxx"
    )
);

But I need send to the API

headers => array(
        "client_id"=>"xxxx",
        "client_secret"=>"xxxxxx"
);

**Comment by phalcondroid** [comment]
Si quieres explica en español para entenderte mejor Diego

**Comment by phalcondroid** [comment]
Tu no puedes enviar arrays por post a menos que sea un raw body, si quieres enviarlos por post siempre debes enviar un clave valor, eso en phalcon o donde sea,  incluso por Curl, lo que debes hacer es recorrer tu index field y asignarlos con el ->set() ....

**Comment by mbermeo** [comment]
Hola, gracias por respondernos phalcondroid.

Resulta que estamos trabajando con incubator, no hemos tenido ningún inconveniente con los consumos de APIs por post, es decir, cuando tratamos de consumir un endpoint por post, enviamos las variables y el servicio nos responde correctamente.

El inconveniente que tenemos ahora es que un servicio requiere que aparte de las variables POST, sele envíen 2 variables por medio de los headers (client_id y client_secret).

Cuando tratamos de armar el objeto con incubator, nos dimos cuenta que este lo que hace es crear las variables nuestras dentro de otra llamada "fields" y cuando hacemos la petición, efectivamente el endpoint que consumimos nos dice que nos faltan las variables client_id y client_secret.

La pregunta puntual es: Hay alguna forma de con incubator crear variables en los headers por fuera de fields.

De nuevo gracias.

**Comment by sergeyklay** [comment]
@diegomurbanos Could you please provide a small script to reproduce?

**Comment by diegomurbanos** [comment]
Thank you @sergeyklay @phalcondroid the problem was directly the API and not the frontend client, sorry for the disturb we are learning phalcon :)

**Comment by phalcondroid** [comment]
$request = Phalcon\Http\Client\Request::getProvider();
$provider = $request::getProvider();
var_dump($provider->setOption(CURLOPT_HTTPHEADER, array('HeaderName: HeaderValue')));

Prueba con esto...
