### ISSUE TITLE
Oracle PDO: Class phalcon\db\dialect\oracle

### ISSUE THREAD

**Issue by mnashmi** [phalcon/incubator#663]
Fatal error: Class 'phalcon\db\dialect\oracle' not found in ....

```php
$test = new \Phalcon\Db\Adapter\Pdo\Oracle([
            'username'    => '',
            'password'    => '',
            'dbname'      => ''
        ]);
```

```php

$loader->registerNamespaces([
    ...
    'Phalcon'           =>  BASE_PATH.  $config->application->libraryDir.'Phalcon/'
])->register();

```

I think its the lower case search, i manually changed the constructor to the following which works :

```php
public function __construct(array $descriptor){
        $this->connect($descriptor);

         $dialectClass = '';
         $connectionId = '';

         $this->_dialect = new \Phalcon\Db\Dialect\Oracle;
         $this->_descriptor = $descriptor;
    }

```

I think the problem is in the core source in the file: phalcon/db/adapter.zep at line 119.

```zephir
let dialectClass = "phalcon\\db\\dialect\\" . this->_dialectType;
```

should become:
```
let dialectClass = "Phalcon\\Db\\Dialect\\" . this->_dialectType;
```

**Comment by sergeyklay** [comment]
Provide please Incubator **and** Phalcon version

**Comment by mnashmi** [comment]
3.0.1 - both master in github.

**Comment by sergeyklay** [comment]
> let dialectClass = "phalcon\\db\\dialect\\" . this->_dialectType;

Zephir uses case insensitive search

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by MLukman** [comment]
Hello sir, may I know if there's any progress on this issue?

**Comment by sergeyklay** [comment]
@MLukman I'll try to sort out ASAP. I'm sorry for delay

**Comment by sergeyklay** [comment]
Can't reproduce.

```
$ mkdir test
$ cd test
$ git clone git@github.com:phalcon/incubator.git
$ cd incubator
$ git checkout 3.0.x
$ vim test.php
```

```php
<?php

use Phalcon\Loader;

$loader = new Loader();
$loader->registerNamespaces([
  'Phalcon' => '/project/test/incubator/Library/Phalcon/'
]);
$loader->register();

assert(class_exists("Phalcon\\Db\\Dialect\\Oracle") === true);
assert(class_exists("Phalcon\\Db\\Adapter\\Pdo\\Oracle") === true);

echo "Ok", PHP_EOL;

assert(class_exists("phalcon\\db\\dialect\\oracle") === true);
assert(class_exists("phalcon\\db\\adapter\\pdo\\oracle") === true);

echo "Ok", PHP_EOL;

$connection = new Phalcon\Db\Adapter\Pdo\Oracle([
  'username'     => 'oracle',
  'password'     => 'oracle',
  'dbname'       => '//localhost/enigma',
  'dialectClass' => Phalcon\Db\Dialect\Oracle::class
]);

echo "Ok", PHP_EOL;
```

```
$ php test.php
Ok
Ok
Ok
```

```
php -m | egrep -i "(oci|phalcon)"
oci8
PDO_OCI
phalcon
```

**Comment by lubberscorrado** [comment]
Found the issue: @sergeyklay testcase is of course working fine, because it is instantiating the dialect class directly in php.
The issue still happens when the Zephir Adapter tries to access the incubator Oracle Dialect by itself (within the c-extension part of Phalcon), just like the example @mnashmi has given.

The workaround, which will also help @mnashmi is your last testcase: Give the dialectClass directly to the $connection:

`dialectClass' => Phalcon\Db\Dialect\Oracle::class`

If you omit the dialectClass and let the Zephir compiled Adapter Parent Class do it, it will fail and could not find the dialectClass

So i think this is still something to fix in Zephir.
