### ISSUE TITLE
Encrypt Session Cookie

### ISSUE THREAD

**Issue by RayHughes** [phalcon/incubator#668]
When using this adapter, session cookies are not encrypted in the browser. Phalcon's crypt library seems to have no effect on this library.

**Comment by RayHughes** [comment]
Any insight?

**Comment by Jurigag** [comment]
What you mean by this adapter?

**Comment by RayHughes** [comment]
https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Session/Adapter

**Comment by Jurigag** [comment]
And which exactly one? Why closed issue? Is it working now?

**Comment by RayHughes** [comment]
No. I closed and opened with more info
