### ISSUE TITLE
Missing isset() and default (null?) return value if !isset

### ISSUE THREAD

**Issue by cottton** [phalcon/incubator#685]
see https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Http/Client/Header.php#L71

On calling `get($name)` we run into a undefined index.

I know about the `has` method. But imo it should check if is set, and if not return null.

Thanks,
cottton

**Comment by sergeyklay** [comment]
I think `array_key_exists` better fix

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
