### ISSUE TITLE
Http/Client/Provider/Curl CURLOPT_HEADERFUNCTION memory problem / __destruct not called. 

### ISSUE THREAD

**Issue by cottton** [phalcon/incubator#689]
_Took me 4 hours (or more) to find out why the curl provider eats memory._

**Test**:

    #$client = new \Phalcon\Http\Client\Provider\Curl();
    while (1) {
        $client = new \Phalcon\Http\Client\Provider\Curl();
        $client->get("http://localhost"); // or post, put, ... (any)
        var_dump(memory_get_usage());
    }
    
    // "phalcon/incubator": "3.0.x",
    // PHP_VERSION 7.0.11

**What happen:**
- endless loop using curl provider (on each loop new or same instance does not make a difference)
- do a post, put, get, ... request
- output memory usage

**What happen wrong:**
- memory usage grows until limit reached

**Why:**
_Line:_ https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Http/Client/Provider/Curl.php#L119
`CURLOPT_HEADERFUNCTION` is the bad guy.
The **callback** causes _who/where ever_ to **hold** a **reference** of $this (Provider/Curl).
And because of $this :) the `__destruct` **does not get called**.
And _(now guessing)_ because of no `__destruct` there is a **zombie** instance of Provider/Curl which f* up the memory.

**Solution:**
Not using `CURLOPT_HEADERFUNCTION`
or `$this->setOption(CURLOPT_HEADERFUNCTION, null);` after `curl_exec`

_I saw the PR when it has been added. But ... why it has been added oO?
A `foreach` could do the job._
 
**So to change less code i think the `null` version is the better way to fix that.
Will create PR soon.**

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.

**Comment by cottton** [comment]
Would like to re-open this because this fix brought a new bug (sorry for that).

`$this->setOption(CURLOPT_HEADERFUNCTION, null);` fixed the problem where the destuct did not get called.
But this line MUST be below `if ($errno = curl_errno($this->handle)) {`
beacuse otherwise a previous occurred curl error gets unset.

Test:

    while (1) {
        $client = new \Phalcon\Http\Client\Provider\Curl();
        $response = $client->get("http://foo.bar");
        var_dump($response->header->status);
        var_dump(memory_get_usage());
    }
    
    // "phalcon/incubator": "3.0.x",
    // PHP_VERSION 7.0.11

Out:

> string(0) ""
int(944984)
string(0) ""
int(944984)
...

**What happen?**
Actually we would have thrown an exception. But because the crl error got reset by setOption
the response came through without any kind of data.

**How to Fix?**
Moving the destruct fix as far as possible "to the bottom" 
See PR https://github.com/phalcon/incubator/pull/726
