### ISSUE TITLE
Nested set behaviour not work with Postgresql and Phalcon 3

### ISSUE THREAD

**Issue by esoftcard** [phalcon/incubator#694]
I have tried to intergrated this to project, but this seem not work 
https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Behavior/NestedSet.php

**Comment by sergeyklay** [comment]
Could you please provide a bit more information.

**Comment by esoftcard** [comment]
I have created Model with : lft, rgt, root, level, title attribute
Install Incubator, tested with Slug is OK=> so behaviour should work.
In controller, I set as example: 
addAction with folow: 
```
public function addAction()
    {
        $root = new Category();
        $root->title = 'Cars';
        $root->saveNode();
        $this->view->disable();
    }
```
Model:
```
use Phalcon\Mvc\Model;
use Phalcon\Mvc\Model\Behavior\NestedSet as NestedSetBehavior;

class Category extends \Phalcon\Mvc\Model
{
	public $id;
	public $lft;
	public $rgt;
	public $root;
	public $level;
	public $title;
	public $slug;
	
	public function initialize()
	{
		$this->addBehavior(new NestedSetBehavior(array(
			'rootAttribute'  => 'root',
            'leftAttribute'  => 'lft',
            'rightAttribute' => 'rgt',
            'levelAttribute' => 'level',
		)));
	}
}
```
But it doesn't work. Nothing save to database, no error noticed

**Comment by sergeyklay** [comment]
Provide please table schema

**Comment by esoftcard** [comment]
Here is it:

lft: integer 
rgt: integer 
level: integer 
title: varchar
slug: varchar
root: integer
parent_id: integer
id: primary key 

table without any Foreign key

**Comment by sergeyklay** [comment]
I'll try to sort out ASAP.

**Comment by esoftcard** [comment]
thank you , hope to receive your reply soon about this

**Comment by esoftcard** [comment]
is there any update ?

**Comment by sergeysviridenko** [comment]
There isn't any reaction. I propose to close this issue. If problem will appear again, we open new one.
