### ISSUE TITLE
The entire Firebug extension has been discontinued

### ISSUE THREAD

**Issue by dschissler** [phalcon/incubator#702]
Is there any other potential technology in any browser that could provide the header based logging that was possible with Firebug + Firelogger?

**Comment by jellisii** [comment]
Could possibly use http://log4javascript.org/docs/manual.html along with it's `getHeaders()` method to create something.

**Comment by sergeysviridenko** [comment]
I propose move this issue to forum. This isn't any bugs or proposition of features. How do you think @sergeyklay ?

**Comment by sergeyklay** [comment]
We'll need to remove obsolete or/and abandoned code from the incubator. Phalcon Incubator isn't an archive of everything in the world. In this repository we welcome submissions from the community of libraries that could extend  the framework more and may be moved to the Phalcon in future.
