### ISSUE TITLE
Subcollection in MongoCollection

### ISSUE THREAD

**Issue by tkroll** [phalcon/incubator#722]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Expected.**

Using Phalcon\Mvc\Collection with old mongo driver, subcollection returned as arrays

> **Actual.**

Using Phalcon\Mvc\MongoCollection with mongodb driver, subcollection is StdClass

### Details

Fixed by changing line 303. See https://forum.phalconphp.com/discussion/15261/sub-collection-access-in-mongocollection-vs-collection

* Phalcon Framework version: 3.03
* Phalcon Incubator version: 3.0x
* PHP Version: PHP 7.0.8-0ubuntu0.16.04.3
* Operating System: Ubuntu 16.04
* Server: Apache

**Comment by sergeyklay** [comment]
Fixed in the `3.0.x` branch.
