### ISSUE TITLE
Curl error lost/reset/broke due to #690

### ISSUE THREAD

**Issue by cottton** [phalcon/incubator#729]
_As written here (but was already closed so nw issue here) https://github.com/phalcon/incubator/issues/689#issuecomment-277010236_
 
`$this->setOption(CURLOPT_HEADERFUNCTION, null);` fixed the problem where the destuct did not get called.
But this line MUST be below `if ($errno = curl_errno($this->handle)) {`
beacuse otherwise a previous occurred curl error gets unset.

**Test:**

Expecting
> Fatal error: Uncaught Phalcon\Http\Client\Exception: Could not resolve host: foo.bar in /var/www/html/vendor/phalcon/incubator/Library/Phalcon/Http/Client/Provider/Curl.php:155

code

    while (1) {
        $client = new \Phalcon\Http\Client\Provider\Curl();
        $response = $client->get("http://foo.bar");
        var_dump($response->header->status);
        var_dump(memory_get_usage());
    }
    
    // "phalcon/incubator": "3.0.x",
    // PHP_VERSION 7.0.11

Out:
> string(0) ""
int(944984)
string(0) ""
int(944984)
...

Using the fix (see below #726 ) the result is (as expected):

> Fatal error: Uncaught Phalcon\Http\Client\Exception: Could not resolve host: foo.bar in /var/www/html/vendor/phalcon/incubator/Library/Phalcon/Http/Client/Provider/Curl.php:155

**What happen?**
Actually we would have thrown an exception. But because the crl error got reset by setOption
the response came through without any kind of data.

**How to Fix?**
Moving the destruct fix as far as possible "to the bottom" 
See PR https://github.com/phalcon/incubator/pull/726

**What was the destruct fix?**
`$this` (Provider\Curl) got _stuck_ in `CURLOPT_HEADERFUNCTION`. Destruct got never called.

**Question**
PR tests failed but seems not related to my changes oO?
See: https://travis-ci.org/phalcon/incubator/jobs/197706451#L768

**Comment by cottton** [comment]
_this is a bug and imo high prior_ -bump

**Comment by sergeyklay** [comment]
@cottton Could you please send a PR?

**Comment by cottton** [comment]
There is already one: https://github.com/phalcon/incubator/pull/726
I have no idea why the tests failed.
Should i create a new one?

**Comment by sergeyklay** [comment]
Well, merged. Can we safely close this issue?

**Comment by cottton** [comment]
yes
