### ISSUE TITLE
CURLOPT_HEADER will not be true by default in Phalcon\Http\Client

### ISSUE THREAD

**Issue by elcreator** [phalcon/incubator#732]
```php
    private function initOptions()
    {
        $this->setOptions([
            CURLOPT_RETURNTRANSFER  => true,
            CURLOPT_AUTOREFERER     => true,
            CURLOPT_FOLLOWLOCATION  => true,
            CURLOPT_MAXREDIRS       => 20,
            CURLOPT_HEADER          => true, // please remove this
```

now library returns headers in two places: concatenated with response and in headers field.
of course, $fullResponse = false. (headers will be doubled in content if true)

**Comment by elcreator** [comment]
```php
        $params = ['key' => 'secret', 'param' => 'value'];
        $this->_apiClient = Request::getProvider();
        $this->_apiClient->setBaseUri($this->_baseUri);
        $this->_apiClient->header->set('Content-Type', 'application/json');
        $response = $this->_apiClient->post($path, json_encode($params));
        echo $response->body; // now outputs headers concatenated with response body
```

**Comment by sergeyklay** [comment]
Cc: @cottton

**Comment by cottton** [comment]
Which framework **version**?
Im using 3.0.3 here 
`CURLOPT_HEADER` is default `false`.
see https://github.com/phalcon/incubator/blob/3.0.x/Library/Phalcon/Http/Client/Provider/Curl.php#L80

Try `$client->setOption(CURLOPT_HEADER, false);` before `->post(...)`.

Here a test on a live test-api:

    $baseUri = 'https://jsonplaceholder.typicode.com';
    $path = '/posts';
    $params = ['key' => 'secret', 'param' => 'value'];
    $apiClient = \Phalcon\Http\Client\Request::getProvider();
    $apiClient->setBaseUri($baseUri);
    $apiClient->header->set('Content-Type', 'application/json');
    
    $apiClient->setOption(CURLOPT_HEADER, false);
    
    $response = $apiClient->post($path, json_encode($params), true, [], false);
    
    echo "Provider: " . get_class($apiClient) . PHP_EOL;
    echo "Response: " . PHP_EOL;
    var_dump($response->body);

Out:

    Provider: Phalcon\Http\Client\Provider\Curl
    Response: 
    string(54) "{
      "key": "secret",
      "param": "value",
      "id": 101
    }"

**Comment by elcreator** [comment]
2.1.x https://github.com/phalcon/incubator/blob/2.1.x/Library/Phalcon/Http/Client/Provider/Curl.php#L78

**Comment by sergeyklay** [comment]
The 2.1.x is no longer supported. You have to use v3 or override the class, making the necessary corrections.
