### ISSUE TITLE
Beanstalk extended / Fork helper issue

### ISSUE THREAD

**Issue by sergeyklay** [phalcon/incubator#743]
Hello @duncan3dc

I've created this issue to show you main problem with Beanstalk extended / Fork helper.
Build failed: https://travis-ci.org/phalcon/incubator/jobs/209075699

Sometimes this happens with PHP 7, sometimes with PHP 5.6, sometimes all ok.

Failed only this test: https://github.com/phalcon/incubator/blob/3.0.x/tests/unit/Queue/Beanstalk/ExtendedTest.php#L186-L194

Could you please take a look?

---------

Refs: https://github.com/phalcon/incubator/pull/672

**Comment by duncan3dc** [comment]
Hi @sergeyklay, how can I just run the `Beanstalk` tests? I used to use `phpunit` but it looks like this repo doesn't work with it anymore:
```
git@idf504721:/tmp/incubator$ phpunit tests/unit/Queue/Beanstalk/ExtendedTest.php 
PHP Fatal error:  Class 'Codeception\TestCase\Test' not found in /tmp/incubator/tests/unit/Queue/Beanstalk/ExtendedTest.php on line 27
```

**Comment by sergeyklay** [comment]
@duncan3dc You can see all steps at .travis.yml

**Comment by duncan3dc** [comment]
@sergeyklay But that runs the entire test suite, I only want to test the `Beanstalk` namespace

**Comment by sergeyklay** [comment]
Yes `codeception run relative/path/to/the/test/file/here` :)

**Comment by duncan3dc** [comment]
Thanks @sergeyklay, but it still looks like that runs unrelated code (the `Beanstalk` tests don't require a PDO connection do they?):
```
git@idf504721:/tmp/incubator$ codeception run -vvv tests/unit/Queue/Beanstalk/ExtendedTest.php 
Codeception PHP Testing Framework v2.2.9
Powered by PHPUnit 4.8.35 by Sebastian Bergmann and contributors.

                                                                               
  [Codeception\Exception\ModuleException]                                      
  Db: SQLSTATE[HY000] [2002] Connection refused while creating PDO connection  
```

**Comment by sergeyklay** [comment]
@duncan3dc Ho yes... Could you please open `unit.suite.yml` and disable database initialization by comment module Db: https://github.com/phalcon/incubator/blob/master/tests/unit.suite.yml#L14
