### ISSUE TITLE
MongoCollection datatypes

### ISSUE THREAD

**Issue by armonb** [phalcon/incubator#750]
Since v3.0.4 (commit 898ea411565091f33d9249c429674dfcccaf36a4)

When retrieving documents from a mongo database using Phalcon\Mvc\MongoCollection ,  all objects are now retrieved as arrays ignoring the data type originally specified.

I assume this is due to the change on line 303.

**Comment by kpasokhi** [comment]
I confirm this issue. We used objects in our entire project but this change broken our code.
Please revert datatype to object.

**Comment by tigerstrikemedia** [comment]
I think there has been several issues around this, I do not have a copy currently that I can create a pull request with, I can write some code, test and create one later on tonight or tomorrow morning.

I think the solution that would be most flexible, and easily adaptable for everyones code would be to set the typemap as a property on the class. EG:

```
abstract class MongoCollection extends PhalconCollection implements Unserializable
{
    // @codingStandardsIgnoreStart
    static protected $_disableEvents;
    // @codingStandardsIgnoreEnd

    var $_typemap = [ 
        'root'           => '', //Need some way to integrate this with get_class($base) 
        'document' => 'object', 
        'array'         => 'array'
    ]
```

**Comment by sunz5010** [comment]
I have the same problem

**Comment by Jeckerson** [comment]
Try to use `phalcon/incubator-mongodb@v2.0.0`
