### ISSUE TITLE
Remove PHP 5.4 notice in /Phalcon/Mvc/Model namespace

### ISSUE THREAD

**Issue by dschissler** [phalcon/incubator#759]
https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Mvc/Model: `PHP versions under 5.4 do not support traits, use instead Phalcon\Mvc\Model\EagerLoading\Loader methods`.

Does anything else need to be cleaned up with this?

**Comment by sergeyklay** [comment]
@dschissler Incubator does not support PHP 5.4
https://github.com/phalcon/incubator/blob/master/.travis.yml#L17

Could you please explain a bit more?

**Comment by dschissler** [comment]
Look at the bottom of the link and you will see the text that I quoted.  It is an old notice about PHP 5.4 and below.  I'd make a pull request but I don't know if there are other things to cleanup as well.  I just noticed this when I was browsing around in the code.

**Comment by sergeyklay** [comment]
Ah, got it. Yah, we need to remove this
