### ISSUE TITLE
MongoCollection: Save does not only write attributes

### ISSUE THREAD

**Issue by ktrhn** [phalcon/incubator#762]
**Behaviour**

When creating a new MongoCollection object, setting a property and then saving it, all the private fields, and not only the attributes, are saved as well.

```
class User extends Phalcon\Mvc\MongoCollection
{
    public function getSource()
    {
        return 'users';
    }
}

$user = new User();
$user->name = 'Robert';
$user->save();
```

**Result**

<img width="632" alt="2017-04-22 13-09-02" src="https://cloud.githubusercontent.com/assets/5049311/25303928/f4d29720-275c-11e7-8614-4ede1b85539f.png">

**Expected**

Only _id and name gets set in the document.

**Versions**

* Phalcon Framework version: 3.1.2
* Phalcon Incubator version: 3.1.1
* PHP Version: 7.1.4
* Operating System: OS X
* Server: nginx

**Comment by Jurigag** [comment]
I wonder if the same happens for php5 and Phalcon\Mvc\Collection?

**Comment by tkroll** [comment]
@Jurigag Works fine for me

PHP 5.6.23
Phalcon 2.0.10
Mongo 3.0.14

**Comment by dereckmartin** [comment]
I have the same issue with PHP7.1, I didn't have this issue on PHP7.0

Phalcon + PHP
```
root@app:~# phalcon -v

Phalcon DevTools (3.1.2)

Environment::
  OS: Linux app 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64
  PHP Version: 7.1.4-1+deb.sury.org~xenial+1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.1
  PHP Extension Dir: /usr/lib/php/20160303
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.1/cli/php.ini
Versions::
  Phalcon DevTools Version: 3.1.2
  Phalcon Version: 3.1.2
  AdminLTE Version: 2.3.6

```

MongoDB
```
root@app:~# mongod --version
db version v3.4.4
git version: 888390515874a9debd1b6c5d36559ca86b44babd
OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
allocator: tcmalloc
modules: none
build environment:
    distmod: ubuntu1604
    distarch: x86_64
    target_arch: x86_64
```

I even installed Mongo 2.6 that you can get from base Ubuntu repository, and I get the same issue:
```
root@app:~# mongod --version
db version v2.6.10
2017-05-02T21:39:54.552-0400 git version: nogitversion
2017-05-02T21:39:54.552-0400 OpenSSL version: OpenSSL 1.0.2g  1 Mar 2016
```

**Comment by dereckmartin** [comment]
I can confirm downgrading to php7.0 resolves the issue:

```
> db.audit.find();
# On PHP-7.1
{ "_id" : ObjectId("590934b3d2a57d04c47873b8"), "ip" : "10.0.2.2", "uri" : "/api", "method" : "GET", "time" : 16.43, "version" : 1, "_dependencyInjector" : {  }, "_modelsManager" : {  }, "_source" : null, "_operationMade" : 1, "_dirtyState" : 1, "_connection" : {  }, "_errorMessages" : [ ], "_skipped" : false }

# On PHP-7.0
{ "_id" : ObjectId("590936d2d2a57d34117f45c2"), "ip" : "10.0.2.2", "uri" : "/api", "method" : "GET", "time" : 234.25, "version" : 1 }
```

PHP version
```
root@app:~# phalcon -v

Phalcon DevTools (3.1.2)

Environment::
  OS: Linux app 4.4.0-75-generic #96-Ubuntu SMP Thu Apr 20 09:56:33 UTC 2017 x86_64
  PHP Version: 7.0.18-1+deb.sury.org~xenial+1
  PHP SAPI: cli
  PHP Bin: /usr/bin/php7.0
  PHP Extension Dir: /usr/lib/php/20151012
  PHP Bin Dir: /usr/bin
  Loaded PHP config: /etc/php/7.0/cli/php.ini
Versions::
  Phalcon DevTools Version: 3.1.2
  Phalcon Version: 3.1.2
  AdminLTE Version: 2.3.6
```

**Comment by Jurigag** [comment]
Yea, it happens only for php 7.1, looks like zephir problem.

**Comment by Jurigag** [comment]
Well i have this even on php 7 for some reason. Like `getReservedAttributes()` just return null.

**Comment by Jurigag** [comment]
This is zephir related bug - https://github.com/phalcon/zephir/issues/1536

**Comment by ktrhn** [comment]
I use the suggestion here https://github.com/phalcon/incubator/issues/760#issuecomment-294846629 as a workaround, seems to be the same problem?

**Comment by Jurigag** [comment]
Also im not sure if i even understand this getReservedAttributes correctly, shouldn't it have ALL protected propertis from `Phalcon\Mvc\Collection` or `Phalcon\Mvc\MongoCollection` ? It looks like get_object_vars in zephir returns values inconsistent?

**Comment by Jurigag** [comment]
In phalcon 3.2 it should be working fine right now.

**Comment by Jurigag** [comment]
If someone still have problems https://github.com/phalcon/incubator/issues/760#issuecomment-309721818 then read this comment and below.

**Comment by aprchen** [comment]
I have some situation here, save can take effect, but the modification and deletion are not effective,
![image](https://user-images.githubusercontent.com/13740363/35610164-3d72ecfa-069b-11e8-8fd7-fdf02dceeedb.png)
It turns out to be the same.
![image](https://user-images.githubusercontent.com/13740363/35610212-6124cb96-069b-11e8-851f-f19e580213c9.png)
When I use the following method, the modification succeeds
![image](https://user-images.githubusercontent.com/13740363/35610256-8cf5171c-069b-11e8-9678-f91406fc9342.png)

MongoDB extension version => 1.3.4
php version =>7.1.11
MongoDB shell version v3.6.2
LSB Version:	:core-4.1-amd64:core-4.1-noarch
Distributor ID:	CentOS
Description:	CentOS Linux release 7.4.1708 (Core)
Release:	7.4.1708
Codename:	Core
