### ISSUE TITLE
Specify in readme how to successfully run tests

### ISSUE THREAD

**Issue by micheleangioni** [phalcon/incubator#764]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

Running all Incubator tests without errors.

> Provide output if related

It's too long to paste the errors I get and probably it's not even the point.

> Provide minimal script to reproduce the issue

```
- run composer install
- add apcu php extension, if missing
- setup tests/.env file
- setup tests/unit.suite.yml file
- run tests/unit.suite.yml
```

### Details

* Phalcon Framework version: 3.1.2
* Phalcon Incubator version: master
* PHP Version: 7.1.4
* Operating System: Ubuntu 16.04
* Server: --

### Explanation

Successfully running all Incubator tests is not straightforward and, moreover, no explanation is provided.

I think it's really vital to write down in the readme the exact procedure to set up the needed configuration to run all tests without errors. In case there are failing or erroring tests, they should be fixed asap.

That would really simplify the life (especially) of new contributors and make it easier to create PR for existing code.

Thanks

**Comment by sergeyklay** [comment]
Actually you can follow [**`.travis.yml`**](https://github.com/phalcon/incubator/blob/master/.travis.yml). Isn't it?

**Comment by tkroll** [comment]
This is indeed needed. There is specifically a problem with incompatibility with Codeception.

**Comment by sergeyklay** [comment]
Well, PR are always welcome

**Comment by micheleangioni** [comment]
@sergeyklay that probably would work, but I would hope into something clearer, even because it is using Travis parameters. At very worst just write in the readme "follow .travis.yml file" but really, this is anything but clear.

We should put ourselves into a new developer shoes and try to make it as easy as possible for him to contribute. I hope that you agree that "follow .travis.yml" is actually not the best advice we could give him :) 

About PRs, imho in this case someone who has some experience with running Incubator tests should do that.

**Comment by tkroll** [comment]
Trying to build the tests locally was a fool's errand. 

I understand Travis now. Works fine 

Thanks for the hint.

**Comment by sergeyklay** [comment]
Well, documentation process has been started. Feel free to amend or send corrections.
