### ISSUE TITLE
MongoDB Uniqueness Validation Model::Update()

### ISSUE THREAD

**Issue by dereckmartin** [phalcon/incubator#766]
### Expected and Actual Behavior

On model validation, uniqueness validation is applied to a field.  In this case 'email'.  If the unique field value in the collection for the given id is same as the record id being updated, the validation should not fail.

```php

// Model
class Users extends MongoCollection
    public $email;

    public function validation()
    {
        $validator = new Validation();
        $validator->add('email', new Uniqueness([
            "message" => "The email is already used"
            ])
        );

        return $this->validate($validator);
    }
}

// Example Action
//
// Mongo Document:
// { "_id" : ObjectId("5910b857d2a57d04844adca8"), "firstname": "test", "lastname":"user", "email":"tuser@example.tld" }
// JSON body:
// { "firstname": "test", "lastname":"user", "email":"tuser@example.tld" }
//
    public function updateAction($id)
    {
        try {
            $result = Users::findById($id);
            $request_body = $this->request->getJsonRawBody();

            $result->firstname = $request_body->firstname;
            $result->lastname = $request_body->lastname;
            // added if statement to show validation error when record has the same value for email
            if ($result->email != $request_body->email) {
                $result->email = $request_body->email;
            }
            $result->update();

            $messages = $user->getMessages();

            $m = [];
            if (count($messages)) {
                foreach ($messages as $msg) {
                    array_push($m, $msg->getMessage());
                }
            }

            $response = Phalcon\Http\Response();
            $response->setJsonContent( [ 'messages' => $m ]);

            return $response;
        } catch (\Exception $e) {

        }
    }

```

Currently, validation is failing when updating a record with a uniqueness field when the old and new value are the same.

### Details

* Phalcon Framework version: (`php --ri phalcon`)

Web framework delivered as a C-extension for PHP
phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.1.2
Build Date => Apr  6 2017 14:16:21
Powered by Zephir => Version 0.9.7-1fae5e50ac

* Phalcon Incubator version: (branch, composer version)

Incubator: ^3.1
Composer version @package_branch_alias_version@ (1.0.0-beta2) 2016-03-27 16:00:34

* PHP Version: (`php -v`)

PHP 7.0.18-1+deb.sury.org~xenial+1 (cli) (built: Apr 11 2017 14:36:44) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.18-1+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies

* Operating System: Ubuntu 16.04 LTS
* Server: Nginx
* Database: MongoDB v3.4.4

**Comment by Jurigag** [comment]
What `$result->getDirtyState()` returns after update?

**Comment by dereckmartin** [comment]
I am commenting and closing.  Reason: Self inflicted pain due to PEPCAK.

I was issuing a POST instead of a PUT, and my createAction was being invoked instead of the updateAction.

Everything works as it should.

**Comment by Jurigag** [comment]
Oh okay. You sure, right, you checked it?

**Comment by Jurigag** [comment]
@dereckmartin well actually it works, but it just most likely it just call exists method when it's not necessary needed, update is needed anyway to improve performance so we could reopen this anyway

**Comment by Jeckerson** [comment]
Try to use `phalcon/incubator-mongodb@v2.0.0`
