### ISSUE TITLE
MongoCollection doesn't have update method

### ISSUE THREAD

**Issue by Jurigag** [phalcon/incubator#794]
Not sure if this is correct or not but there is `Phalcon\Mvc\Collection::update` but yet `Phalcon\Mvc\MongoCollection` doesn't override this method. I think we should have update method with proper code for php 7/7.1 too.

If someone doesn't know what's the difference between update and save - update just updates already existing instance only, save creates or updates instance, depending on operation(if collection exists).

**Comment by micheleangioni** [comment]
I agree with you @Jurigag . With MongoCollection currectly one is forced to always use save(), but it would be nice to have update as well.
