### ISSUE TITLE
Change Phalcon 3.2.0 methods

### ISSUE THREAD

**Issue by hajcu** [phalcon/incubator#797]
Change methods in Blamable.php from hasChanged(), getChangedFields(), getSnapshotData() to hasUpdated(), getUpdatedFields(), getOldSnapshotData()

**Comment by sergeyklay** [comment]
@Jurigag Could you please take a look

**Comment by Jurigag** [comment]
Yea i will update it, i already have waiting branch with this. Try to to it next week.

**Comment by Jurigag** [comment]
Done in 3.2.1
