### ISSUE TITLE
MongoCollection::find now requires fields param to be associative array

### ISSUE THREAD

**Issue by tkroll** [phalcon/incubator#808]
Old code using the fields param as an array now fails with only the _id returned.

`$blah = Blah::find([`
 `'fields' => ['a', b', c'],`
 `'conditions' => ['a' => 1]`
`]);`

Field parms now works when expressed with the field as the key and 1 as the value:

`$blah = Blah::find([`
 `   'fields' => [`
`        'a' => 1,`
`        'b' => 1,`
 `       'c' => 1`
 `   ],`
`    'conditions' => ['a' => 1]`
`]);`

Not sure why this changed. It does match Mongo shell syntax properly.

**Comment by sergeyklay** [comment]
@sergeysviridenko Could you please take a look

**Comment by Jeckerson** [comment]
Try to use `phalcon/incubator-mongodb@v2.0.0`
