### ISSUE TITLE
graphql support

### ISSUE THREAD

**Issue by galki** [phalcon/incubator#814]
graphql is getting popular. after using graphql in a python project i dont want to go back to REST anymore. however phalcon is my only choice in php. i thus desire graphql support. also, i believe support will be inevitable in the near future as graphql overtakes rest/routing/acl - although this is a personal assumption.

there is [various php support](https://github.com/chentsulin/awesome-graphql#lib-php) and as you can see from that list frameworks like laravel and symphony already provide custom support.

please consider creating orm support for graphql (if you dont ill have to learn python/django)

**Comment by lanlin** [comment]
graphql, that's we need.

**Comment by nexlev** [comment]
Yes. GraphQL support is desired.

**Comment by mesaglam** [comment]
Yeah, we want it too...

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
