### ISSUE TITLE
MysqlExtend DATE_SUB support

### ISSUE THREAD

**Issue by ruudboon** [phalcon/incubator#821]
### Expected and Actual Behavior

I've changed auth example of Vokuro to work with datetime field in mysql and stumbled on an error.
When running a count with parameters on my model I get:

Syntax error, unexpected token NUMERIC PLACEHOLDER(?1), near to ' HOUR)', when parsing: SELECT COUNT(*) AS rowcount FROM

```
$attempts = FailedLogin::count([
            'ip = ?0 AND created_at > DATE_SUB(NOW(), INTERVAL ?1 HOUR)',
            'bind' => [
                '127.0.0.1',
                10
            ]
        ]);
```
Running a query like the one below works fine.

SELECT COUNT(*) AS rowcount FROM failed_logins WHERE ip = '127.0.0.1' AND created_at > DATE_SUB(NOW(), INTERVAL 10 HOUR)

I assume it's caused by the the DATE_SUB that isn't supported, but I'm not sure.
I'm running on Phalcon 3.2.2 and using the MysqlExtended dialect class.

**Comment by Jurigag** [comment]
No, you are using it jsut wrong:

It should be `DATE_SUB(NOW(), DATE_INTERVAL(10, 'HOUR')`
