### ISSUE TITLE
Nested Set Validation Problem

### ISSUE THREAD

**Issue by YujiShen** [phalcon/incubator#825]
### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

I am using `Inclusion` validator on a model with NestedSet behavior, when the validation fails, I can not get error message I set. The transaction seems stoped inside `appendTo` method, and said `There is no active transaction`. But it works correctly if I use `saveNode` when validation fails. And if I use `Callback` validator, no issue at all.

### Details

* Phalcon Framework version: 3.2.3
* Phalcon Incubator version: master
* PHP Version: 7.1.5
* Operating System: Linux
* Server: Nginx

**Comment by sergeysviridenko** [comment]
@YujiShen could you provide a little bit more information to reproduce?

**Comment by YujiShen** [comment]
I try to reproduce, but it is good now. Maybe caused by other code. Thanks for your time.
