### ISSUE TITLE
[NFR] Nested Set - pass custom parameters to search query OR implement user callback to modify DB queries

### ISSUE THREAD

**Issue by temuri416** [phalcon/incubator#829]
Hi,

I need to be able to do something like this:

```php
$children = $node->descendants([
    'approved' => 1,
]);
```

What do you think - maybe we need some sort of listener to pass the `$query` from here:

https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Behavior/NestedSet.php#L206

And, to generalize it, call user method before each of the `return $query->execute()` that access the DB?

Thanks!

**Comment by temuri416** [comment]
Maybe what we really need is a support for Event Manager and observers.

**Comment by temuri416** [comment]
Something like this:

https://gist.github.com/temuri416/05b94d7e3491994993a997d150d32ea0#file-nestedset-php-L21

**Comment by Ultimater** [comment]
Very practical need to be able to grab descendants with an extra condition.

I believe the best solution here would be changing `return $query->execute();` to `return $query;` in [descendants](https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/Model/Behavior/NestedSet.php#L202-L220) based on the presence of a 3rd boolean parameter. Then you can extend NestedSet and easily modify the query by adding an extra WHERE clause before executing it.

**Comment by Ultimater** [comment]
A listener could work too. Depends on what people like working with.

**Comment by Ultimater** [comment]
I feel your pain that you'd expect a solution as readable as the code you posted:   

    $children = $node->descendants([
        'approved' => 1,
    ]);

But then we're forgetting about the optional parameters:

    public function descendants($depth = null, $addSelf = false)

and you wind up with:

````
    $children = $node->descendants(null,false,[
        'approved' => 1,
    ]);
````

**Comment by temuri416** [comment]
Right, that's why implementing Events Manager is much cleaner.

**Comment by Ultimater** [comment]
What if we needed three kinds of queries: `approved => 0`, `approved => 1`, and an omitted version? 
Then you're calling a method before descendants in order to toggle some sort of global state.

Searching is rather case specific and shouldn't be toggling a global state in my opinion.

I'd counter-suggest adding a new method.
Perhaps:
```
    $children = $node->descendantsBy([
        'approved' => 1,
    ]);
```

**Comment by temuri416** [comment]
My idea is that query modification is done by implementer:

```php
$eventsManager = new EventsManager;
$eventsManager->attach(BehNestedSet::EVT_TYPE_QUERY, function(Event $event, Criteria $criteria, AbstractNode $node) {
    if ($callback = $node->getQueryModificationCallback()) {
        $callback($criteria);
    }
});
```

Here your ` $node` that implements Nested Set behavior will contain the callback that will do anything it needs.

**Comment by temuri416** [comment]
1. I have also improved `roots()` method in my gist.
2. Perhaps another useful addition would be to fire **cancelable** events with 'modify:' prefix before tree modification takes place: `append()`, `appendTo()`, `moveBefore()` and so on.

**Comment by sergeysviridenko** [comment]
I propose close this issue

**Comment by sergeyklay** [comment]
Implemented in the latest stable release. Feel free to open a new issue if the problem appears again. Thank you for contributing!
