### ISSUE TITLE
Filename error: Traits/EventManagerTrait.php

### ISSUE THREAD

**Issue by rabrowne85** [phalcon/incubator#835]
When using the NestedSet behaviour of the MVC, the latest version of 3.2.x throws an error that `Phalcon\Traits\EventManagerAwareTrait was not found.`

Looking at the source, I feel that the filename is incorrect and should be: T`raits\EventManagerAwareTrait.php` and not `Traits\EventManagerTrait.php`.

Either that, or the trait name needs to be changed to `EventManagerTrait` and the corresponding reference in line 16 of the NestedSet behaviour needs changing.

**Comment by sergeyklay** [comment]
@rabrowne85 Could you please send a fix?

**Comment by sergeyklay** [comment]
// cc: @sergeysviridenko

**Comment by sergeyklay** [comment]
Fixed in the [latest stable release](https://github.com/phalcon/incubator/releases/tag/v3.2.5). 
Thank you for the report, and for helping us make Phalcon better.
