### ISSUE TITLE
MongoDB RuntimeException with message 'Invalid reply to find command.'

### ISSUE THREAD

**Issue by kideny** [phalcon/incubator#841]
### Expected and Actual Behavior
```
[2017-12-07 10:31:53 *9981.7]	ERROR	zm_deactivate_swoole (ERROR 503): Fatal error:
Uncaught exception 'MongoDB\Driver\Exception\RuntimeException' with message 
'Invalid reply to find command.' in 
/yldata01/yulian/obdns/vendor/phalcon/incubator/Library/Phalcon/Db/Adapter/MongoDB/Operation/Find.php:222
Stack trace:
#0 /yldata01/yulian/obdns/vendor/phalcon/incubator/Library/Phalcon/Db/Adapter/MongoDB/Operation/Find.php(222): 
MongoDB\Driver\Server->executeQuery('obd_device.devi...', Object(MongoDB\Driver\Query), Object(MongoDB\Driver\ReadPreferen
```

```php
           $device = $deviceColl::findFirst(
                [
                    [
                        'id' => $id,
                    ]
                ]
            );
```

### Details

* Phalcon Framework version: (`php --ri phalcon`)

phalcon => enabled
Author => Phalcon Team and contributors
Version => 3.2.0
Build Date => Jun 26 2017 12:01:06
Powered by Zephir => Version 0.9.9-868cb1f92b

Directive => Local Value => Master Value
phalcon.db.escape_identifiers => On => On
phalcon.db.force_casting => Off => Off
phalcon.orm.events => On => On
phalcon.orm.virtual_foreign_keys => On => On
phalcon.orm.column_renaming => On => On
phalcon.orm.not_null_validations => On => On
phalcon.orm.exception_on_failed_save => Off => Off
phalcon.orm.enable_literals => On => On
phalcon.orm.late_state_binding => Off => Off
phalcon.orm.enable_implicit_joins => On => On
phalcon.orm.cast_on_hydrate => Off => Off
phalcon.orm.ignore_unknown_columns => Off => Off
phalcon.orm.update_snapshot_on_save => On => On
phalcon.orm.disable_assign_setters => Off => Off

* Phalcon Incubator version: (branch, composer version)

"phalcon/incubator": "^3.2",

* PHP Version: (`php -v`)

PHP 5.6.30 (cli) (built: Jan 19 2017 07:57:06) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.1, Copyright (c) 2002-2017, by Derick Rethans

* Operating System:

centos8.8

* Server: Nginx | Apache | Other

nginx

* Other related info (Database, table schema):

**Comment by kideny** [comment]
phalcon version update to 3.2.4，this error  repeat。

**Comment by sergeyklay** [comment]
> zm_deactivate_swoole (ERROR 503)

Could you please provide a minimal script to reproduce by using Phalcon?

**Comment by kideny** [comment]
// Initialise the mongoDB Alarm connection.
        $di->setShared("mongoAlarm", function () {
            /** @var \Phalcon\DiInterface $this */
            $config = $this->getShared('config');

            if (!$config->mongo->username || !$config->mongo->password) {
                $dsn = 'mongodb://' . $config->mongo->host;
            } else {
                $dsn = sprintf('mongodb://%s:%s@%s',
                    $config->mongo->username,
                    $config->mongo->password,
                    $config->mongo->host
                );
            }
            $options = [
                'connectTimeoutMS' => 200000, 
                'socketTimeoutMS' => 200000,
                'ssl' => false,
                'serverSelectionTryOnce' => false,
            ];
            $mongo = new Client($dsn, $options);
            return $mongo->selectDatabase($this->get('obd')->database->alarm);
        });

mongodb connect config  is here

**Comment by liluoao** [comment]
How to repair it in the end?
