### ISSUE TITLE
Whether to get rid of twig,swiftmailer 's direct dependence

### ISSUE THREAD

**Issue by inhere** [phalcon/incubator#852]

**Comment by sergeyklay** [comment]
Incubator uses twig and swiftmailer as dependencies for its own adapters. Is there a real problem due to fetch those dependencies?

**Comment by inhere** [comment]
I just want to use some of these components.

This direct dependency, I downloaded a lot of useless code.

**Comment by sergeyklay** [comment]
Yet another way is to _clone_ repo and using Phalcon Loader. In this case you can avoid installing extra dependency.
