### ISSUE TITLE
conflict same namespace \Phalcon\Db\Dialect\MysqlExtended on phalcon/devtools

### ISSUE THREAD

**Issue by sverdier** [phalcon/incubator#854]
I used phalcon/devtools and phalcon/incubator and class \Phalcon\Db\Dialect\MysqlExtended exist on devtools and incubator with same namespace \Phalcon\Db\Dialect\MysqlExtended.
If I used dialectClass => MysqlExtended, I have an error because MysqlExtended of phalcon/devtools is used instead of phalcon/incubator.

**Comment by sergeyklay** [comment]
@sergeysviridenko Could you please take a look

**Comment by sergeyklay** [comment]
Fixed in Devtools 3.3.x branch
