### ISSUE TITLE
MongoDB returning _dependencyInjector

### ISSUE THREAD

**Issue by lifewcody** [phalcon/incubator#855]
### Expected and Actual Behavior

> *Expected Results*

( MyModel Object ( [_id] => MongoDB\BSON\ObjectID Object ( [oid] => myMongoId ) ) )

> *Actual Results*

( MyModel Object ( [_id] => MongoDB\BSON\ObjectID Object ( [oid] => myMongoId ) ) [_dependencyInjector:protected] => Phalcon\Di\FactoryDefault Object ( [_services:protected] => Array ( [router] => Phalcon\Di\Service Object ( [_name:protected] => router [_definition:protected] => Phalcon\Mvc\Router [_shared:protected] => 1 [_resolved:protected] => 1 [_sharedInstance:protected] => Phalcon\Mvc\Router Object ( [_dependencyInjector:protected] => Phalcon\Di\FactoryDefault Object *RECURSION* [_eventsManager:protected] . . . )

> Provide minimal script to reproduce the issue

```php
       $models = MyModel::find([[
                "something" => "here"
        ]]);

        $modelArr= array();
        foreach($models as $mode;){
            array_push($modelArr, (array)$model); // toArray() just returns blank
        }
        print_r($modelArr);
        exit();
```

### Details

* Phalcon Framework version: 3.2.2
* Phalcon Incubator version: 3.3.0
* PHP Version: 7.1.11
* Operating System: Ubuntu 17.04 Desktop
* Server: Nginx
* Other related info (Database, table schema): Database: MongoDB

**Comment by Jeckerson** [comment]
Try to use `phalcon/incubator-mongodb@v2.0.0`
