### ISSUE TITLE
MongoDB & MongoCollection - findFirst get all documents and return first (no limit 1)

### ISSUE THREAD

**Issue by borisdelev** [phalcon/incubator#865]
I am pretty sure MongoCollection findFirst (not only in incubator) retrieve all documents and return first one instead of get just one document. But... let explain:

Hi there...I use MongoDB from incubator (https://github.com/phalcon/incubator/tree/master/Library/Phalcon/Db/Adapter )

```php
use Phalcon\Mvc\Collection\Manager;
use Phalcon\Db\Adapter\MongoDB\Client;

// Initialise the mongo DB connection.
$di->setShared('mongo', function () {
    /** @var \Phalcon\DiInterface $this */
    $config = $this->getShared('config');
    
    if (!$config->database->mongo->username || !$config->database->mongo->password) {
        $dsn = 'mongodb://' . $config->database->mongo->host;
    } else {
        $dsn = sprintf(
            'mongodb://%s:%s@%s',
            $config->database->mongo->username,
            $config->database->mongo->password,
            $config->database->mongo->host
        );
    }
    
    $mongo = new Client($dsn);

    return $mongo->selectDatabase($config->database->mongo->dbname);
});

// Collection Manager is required for MongoDB
$di->setShared('collectionManager', function () {
    return new Manager();
});

// Example from one my collection
namespace Collections;

class Tips extends \Phalcon\Mvc\MongoCollection
{
  ... etc
```

And Ive notice something... If you look code at https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Mvc/MongoCollection.php - and search about findFirst (183 line):
```php
    public static function findFirst(array $parameters = null)
    {
        $className = get_called_class();
        /** @var MongoCollection $collection */
        $collection = new $className();
        $connection = $collection->getConnection();
        return static::_getResultset($parameters, $collection, $connection, true);
    }
```
 you will get result from _getResultset function. So, let see how we get just one record: 

```php
        if (isset($params['limit'])) {
            $limit = $params['limit'];
            $options['limit'] = (int)$limit;
            if ($unique) {
                $options['limit'] = 1;
            }
        }
```

**And obviously findFirst will get all documents and return first one instead to get just first document.** 

So my question is- is this wrong or example (first link) is wrong? Did i must use other MongoCollection/Manager for the new Adapter?

One more thing - in that new MongoDB adapted didnt see findFirst... there is findOne. Is it better to use that?

Thank you and... may the force be with you.
Greetings

PS: sorry for my English skills, but hope u understand me

**Comment by cottton** [comment]
Interesting.

`$cursor = $mongoCollection->find($conditions, $options);`
_/Phalcon/Mvc/MongoCollection.php:300_

creates `new Operation\Find` 
_/Phalcon/Db/Adapter/MongoDB/Collection.php:451_

calls `execute` which calls `$server->executeQuery`.
From there on i dont know how the limit is handled. May sombody know how  `\MongoDB\Driver\Server::executeQuery` handles the limit.

**But** what i see is that the `findOne`
_vendor/phalcon/incubator/Library/Phalcon/Db/Adapter/MongoDB/Collection.php:465_
is using a `new Operation\FindOne` which overrides `execute`
and **that** is calling `$document=current($cursor->toArray());`.
So the `findOne` method is getting all and returns one. I guess we shouldnt use this one.
