### ISSUE TITLE
Append root to another category

### ISSUE THREAD

**Issue by wajdijurry** [phalcon/incubator#869]
Is it able to add root node to another category ?
Example:
```
Root1
- Cat1
- Cat 2
Root2
- Cat 1
- Cat 2
```

After moving:
```
Root1
- Cat 1
- Cat 2
- Root2
-- Cat 1
-- Cat 2
```

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com).
