### ISSUE TITLE
Move Swiftmailer and Twig to Composer "suggest" block

### ISSUE THREAD

**Issue by CameronHall** [phalcon/incubator#875]
I believe the libraries used for adapters that the incubator supports should be "suggested" instead of "required". It should be the developer's responsibility to require the library they need opposed to forcing a specific version and/or downloading a library that isn't going to be used. 

My specific case being, that SwiftMailer is up to version six. I'd like to upgrade to that version but I'm held back by this library enforcing version 5.x. It's not the end of the world but it's frustrating and inconvenient.

**Comment by sergeyklay** [comment]
@CameronHall Could you send a patch?

**Comment by CameronHall** [comment]
Thanks @sergeyklay 
> Just released v3.4.3: https://github.com/phalcon/incubator/releases/tag/v3.4.3
