### ISSUE TITLE
Fatal error: Class Phalcon\Db\Dialect\Oracle contains 1 abstract method and must therefore be declared abstract or implement the remaining methods

### ISSUE THREAD

**Issue by Rolando3010** [phalcon/incubator#879]
Tengo tengo mi aplicacion trabajando de manera adecuada en la version de phalcon 3.4.1, pero al instalarla en otro servidor con la version 3.4.2 no trabaja, al intentar loguear mi aplicacion obtengo el siguiente mensaje:

Fatal error: Class Phalcon\Db\Dialect\Oracle contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Phalcon\Db\DialectInterface::sharedLock) in /var/www/html/boaplus/vendor/phalcon/incubator/Library/Phalcon/Db/Dialect/Oracle.php on line 612

estoy trabajando con oracle cliente 12.2
tengo un archivo php que trbaja con oracle 12.2 y este trabaja sin problemas, validando la corrcta instalacion de php y oci8 junto con el PDO_OCI

[root@localhost Dialect]# php -m | egrep -i "(oci|phalcon)"
oci8
PDO_OCI
phalcon

espero puedan apoyarme. saludos

### Details

* Phalcon Framework version: (
Version => 3.4.2)
Powered by Zephir => Version 0.10.10-d1b4cc68d9
* Phalcon Incubator version: (branch, composer version)
[root@localhost Dialect]# php -v
PHP 7.2.11 (cli) (built: Oct 10 2018 10:00:29) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies

* Operating System: centOS/
* Server:Apache
* Other related info (Oracle, BOA):

**Comment by sonykusyana** [comment]
I also experienced problems like this, please help

**Comment by Jeckerson** [comment]
@Rolando3010 Upgrade your phalcon/incubator to the latest 3.4.x version.
