### ISSUE TITLE
Reseting DI on every calling setUp()

### ISSUE THREAD

**Issue by TimurFlush** [phalcon/incubator#882]
Hello,

Line 57: https://github.com/phalcon/incubator/blob/master/Library/Phalcon/Test/Traits/UnitTestCase.php#L57
**What for?**

It after all will reset all services which I specified in the bootstrap file.

**Comment by sergeyklay** [comment]
As I remember this method should be invoked before any test method. Thus it re-initialize test environment and dependencies which may have changed during the  previous test.

**Comment by TimurFlush** [comment]
@sergeyklay But the services that we registered in the bootstrap file will also be reset before testing. Is that right?

**Comment by sergeyklay** [comment]
Usually the bootstrap file should be called once. But this method - before each test

**Comment by TimurFlush** [comment]
@sergeyklay, i sent letter to your email 7 days ago. Read as you will be free please.

**Comment by sergeyklay** [comment]
@TimurFlush Is issue still actual ?

**Comment by TimurFlush** [comment]
@sergeyklay Not actual
