### ISSUE TITLE
Phalcon/incubator now gives runtime exception on composer update

### ISSUE THREAD

**Issue by webbiegoa** [phalcon/incubator#902]
When using composer update I get the following :
[RuntimeException] 
Failed to execute git remote set-url composer 'git@github.com:phalcon/incubator.git' && git rev-parse --quiet --verify '6466f08ce755c4a4399cef8ca9ffc410398ef9a0^{commit}' || (git fetch composer && git fetch --tags composer) 

Am using 
 "phalcon/incubator": "dev-master",
in composer.json

**Comment by Jeckerson** [comment]
Use **"phalcon/incubator": "3.4.3"** instead of "phalcon/incubator": "dev-master"

**Comment by Jeckerson** [comment]
Also, show your composer.json scripts
