### ISSUE TITLE
Gravatar parts deprecated

### ISSUE THREAD

**Issue by dercoder** [phalcon/incubator#907]
Currently i get this error on PHP 7.3

ErrorException: filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated

```php
if (!filter_var($image, FILTER_VALIDATE_URL, FILTER_FLAG_HOST_REQUIRED)) {
    throw new InvalidArgumentException('The default image specified is not a recognized gravatar "default" and is not a valid URL');
} else {
    $this->defaultImage = $image;
}
```

* Phalcon Framework version: 3.4.4
* Phalcon Incubator version: 3.4
* PHP Version: 7.3

**Comment by Jeckerson** [comment]
Please try with https://github.com/phalcon/incubator-avatar
