### ISSUE TITLE
Status Update - v4

### ISSUE THREAD

**Issue by ruudboon** [phalcon/incubator#911]
This post isn't complete yet.

# WIP
Goal is to upgrade incubator to v4 and keep all functionality and only remove functionality that now is part of the v4 framework. Incubator will be separated into components that will have his own repository (starting with incubator-*) so it will be possible to install only needed components.

## Candidates for removal (checked are approved)
- [x] Phalcon\Acl\Factory\Memory
- [x] Phalcon\Annotations\Extended\Adapter\Apc
- [x] Phalcon\Annotations\Extended\Adapter\Files
- [x] Phalcon\Annotations\Extended\Adapter\Memory
- [x] Phalcon\Annotations\Extended\AbstractAdapter
- [x] Phalcon\Annotations\Extended\AdapterInterface
- [x] Phalcon\Logger\Adapter\File\Multiple
- [x] Phalcon\Legacy
- [x] Phalcon\Config\Loader
- [ ] Phalcon\Db\Factory
- [ ] Phalcon\Http\Client
- [ ] Phalcon\Http\Request

- [x] Phalcon\Logger\Adapter\Firelogger
- [x] Phalcon\Logger\Formatter\Firelogger

- [x] Phalcon\Validation\Validator\Db\Uniqueness
- [x] Phalcon\Validation\Validator\ArrayInclusionIn
- [x] Phalcon\Validation\Validator\CardNumber
- [x] Phalcon\Validation\Validator\ConfirmationOf
- [x] Phalcon\Validation\Validator\Decimal
- [x] Phalcon\Validation\Validator\Ip
- [x] Phalcon\Validation\Validator\NumericValidator

## Needed upgrade (checked is done)
- [x] Phalcon\Acl\Adapter\Database
- [x] Phalcon\Acl\Adapter\Mongo
- [x] Phalcon\Acl\Adapter\Redis
- [ ] Phalcon\Annotations\Adapter\Aerospike
- [ ] Phalcon\Annotations\Adapter\Memcached
- [ ] Phalcon\Annotations\Adapter\Redis
- [ ] Phalcon\Avatar\Gravatar
- [ ] Phalcon\Cache\Backend\Database
- [ ] Phalcon\Cache\Backend\NullCache
- [ ] Phalcon\Cache\Backend\WinCache
- [ ] Phalcon\Cli\Console\Extended
- [ ] Phalcon\Cli\Console\Environment
- [ ] Phalcon\Cli\Console\EnvironmentAwareInterface
- [ ] Phalcon\Cli\Console\EnvironmentInterface
- [ ] Phalcon\Cli\Input\ArgumentInterface
- [ ] Phalcon\Cli\Input\OptionInterface
- [ ] Phalcon\Cli\Input\ParameterInterface
- [x] Phalcon\Config\Adapter\Xml
- [ ] Phalcon\Db\Adapter\Cacheable\Mysql
- [x] Phalcon\Db\Adapter\Mongo\*
- [x] Phalcon\Db\Adapter\MongoDb\*
- [ ] Phalcon\Db\Adapter\Pdo\Oracle
- [ ] Phalcon\Error\Application
- [ ] Phalcon\Error\Error
- [ ] Phalcon\Error\Handle
- [ ] Phalcon\Http\Response\StatusCode
- [ ] Phalcon\Http\Uri
- [x] Phalcon\Logger\Adapter\Database
- [x] Phalcon\Logger\Adapter\Udplogger
- [x] Phalcon\Mailer\Manager
- [x] Phalcon\Mailer\Message

- [x] Phalcon\Validation\Validator\AlphaCompleteValidator
- [x] Phalcon\Validation\Validator\AlphaNamesValidator
- [x] Phalcon\Validation\Validator\AlphaNumericValidator
- [x] Phalcon\Validation\Validator\ArrayInclusionIn
- [x] Phalcon\Validation\Validator\Decimal
- [x] Phalcon\Validation\Validator\Iban
- [x] Phalcon\Validation\Validator\MongoId
- [x] Phalcon\Validation\Validator\PasswordStrength
- [x] Phalcon\Validation\Validator\ReCaptcha

# Modules currently in development
- [Phalcon\Annotations](https://github.com/phalcon/incubator-annotations)
- [Phalcon\Avatar](https://github.com/phalcon/incubator-avatar)
- [Phalcon\Cache](https://github.com/phalcon/incubator-cache)
- [Phalcon\Cli](https://github.com/phalcon/incubator-cli)
- [Phalcon\Config](https://github.com/phalcon/incubator-config)
- [Phalcon\Db](https://github.com/phalcon/incubator-db)
- [Phalcon\Error](https://github.com/phalcon/incubator-error)
- [Phalcon\Http](https://github.com/phalcon/incubator-http)
- [Phalcon\Mailer](https://github.com/phalcon/incubator-mailer)
- [Phalcon\Validation](https://github.com/phalcon/incubator-validation)

**Comment by Jeckerson** [comment]
https://github.com/phalcon/incubator-acl

**Comment by Jeckerson** [comment]
https://github.com/phalcon/incubator-session

**Comment by Jeckerson** [comment]
https://github.com/phalcon/incubator-test

**Comment by Jeckerson** [comment]
https://github.com/phalcon/incubator-logger

**Comment by Jeckerson** [comment]
https://github.com/phalcon/incubator-config
