### ISSUE TITLE
V4: Can't install for phalcon v4

### ISSUE THREAD

**Issue by maxttor** [phalcon/incubator#917]
when I try to install 4.0.x version i get error about version of phalcon

composer:
{
    "require": {
        "phalcon/incubator": "4.0.x"
    }
}

Error:
Problem 1
    - The requested package phalcon/incubator 4.0.x is satisfiable by phalcon/incubator[4.0.x-dev] but these conflict with your requirements or minimum-stability.

### Details

* Phalcon Framework version: 4.0.0-beta.2
* Phalcon Incubator version: 4.0.x
* PHP Version: 7.2.18
* Operating System: ubuntu16.04.1
* Server: Nginx

**Comment by ruudboon** [comment]
Incubator 4.0.x is not released yet. Phalcon 4 is still in beta and we're in the process of upgrading all the related packages. See https://github.com/phalcon/incubator/issues/911 also.
