### ISSUE TITLE
write concern object cannot be empty when I use "findOneAndUpdate"

### ISSUE THREAD

**Issue by sunz5010** [phalcon/incubator#930]
my incubator version is "3.4"
when I upgrade MongoDB from 4.0 to 4.2
it shows `write concern object cannot be empty` when I use `findOneAndUpdate` command
I have to add option

```php
'writeConcern' => new \MongoDB\Driver\WriteConcern(\MongoDB\Driver\WriteConcern::MAJORITY),
```

it works on MongoDB 4.0 if I didn't give writeConcern, but it not works on 4.2 version

**Comment by aadi99999** [comment]
I am facing the same issue.

**Comment by raizadattn** [comment]
Hi All, i am also facing the same issue, is this resolved on 4.4.2?

**Comment by sakurallj** [comment]
I am facing the same issue. But ...   Finally I use the  mongodb package (https://packagist.org/packages/mongodb/mongodb)

**Comment by Jeckerson** [comment]
Try to use `phalcon/incubator-mongodb@v2.0.0`
