### ISSUE TITLE
PHPUnit 8 not supported

### ISSUE THREAD

**Issue by pedroresende** [phalcon/incubator#931]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

When I attempt to use PHPUnit 8, I have the following error 
```
Declaration of Phalcon\Test\PHPUnit\UnitTestCase::setUp() must be compatible with PHPUnit\Framework\TestCase::setUp(): void in /vendor/phalcon/incubator/Library/Phalcon/Test/PHPUnit/UnitTestCase.php on line 31
```

### Details

* Phalcon Framework version: 3.4.4
* Phalcon Incubator version: 3.4
* PHP Version: 7.2.23
* Operating System: Debian 9

**Comment by Jeckerson** [comment]
Duplicate - https://github.com/phalcon/incubator/issues/888

For now, use `phpunit v7`.
