### ISSUE TITLE
[Discussion] Separate Incubator components into own repositories

### ISSUE THREAD

**Issue by Jeckerson** [phalcon/incubator#935]
Most of users of current package, normally, using single or just few classes from whole repository. And, even some times, that logic is going into production...

My purpose is to separate each component of logic (full list located here - https://github.com/phalcon/incubator/issues/911) into separate repositories and at the end, inside composer.json, have something like this:

```
"phalcon/incubator-acl": "0.1",
"phalcon/incubator-db-mongo": "0.1",
"phalcon/incubator-avatar-garavatar": "0.1"
```

Current approach will give possibility to:
* [+] Choose only those packages, that are really need
* [+] Easier to fork, update and use your own implementation
* [+] Easier to support

But:
* [-] More repositories to handle and support
* [-] Probably more some, that I can't manager atm

**Comment by ruudboon** [comment]
I like this idea. That way we can easily migrate parts to v4.
Would be good to define a naming standard for project and namespaces.

**Comment by ruudboon** [comment]
I think we can close this issue and agree this is the way we would like to support incubator in the future. Let's use #911 to track progress.
