### ISSUE TITLE
Issue after upgrading phalcon to 4.0.2

### ISSUE THREAD

**Issue by webbiegoa** [phalcon/incubator#938]
I have set in my composer.json
 "phalcon/incubator": "^3.4.6",

I get the following:
- Installation request for phalcon/incubator ^3.4.6 -> satisfiable by phalcon/incubator[v3.4.6].
- phalcon/incubator v3.4.6 requires ext-phalcon ^3.3 -> the requested PHP extension phalcon has the wrong version (4.0.2) installed.

**Comment by ruudboon** [comment]
Incubator isn't compatible with Phalcon 4 yet.

**Comment by f-do** [comment]
Do you have an idea for the release date (v4)?

**Comment by ruudboon** [comment]
Not yet. We need to look into what parts we can support. Some services aren't available anymore for 7.4.
What part(s) do you currently need?
You could try force install with `ignore-platform-reqs`

**Comment by pushkidman** [comment]
> 
> 
> Not yet. We need to look into what parts we can support. Some services aren't available anymore for 7.4.
> What part(s) do you currently need?
> You could try force install with `ignore-platform-reqs`

Nope, does not work. Is there any other temporary work-around for this?

**Comment by wajdijurry** [comment]
I am facing compatibility issues with Phalcon v4.x too.
One of them is removing ODM, that is, I am using Collection Manager provided by incubator.

**Comment by ruudboon** [comment]
Closing this in favour of https://github.com/phalcon/incubator/issues/911
