### ISSUE TITLE
When can I support Phalcon 4

### ISSUE THREAD

**Issue by wcj343169893** [phalcon/incubator#940]
is branch 4.0.x support phalcon4？

**Comment by Jeckerson** [comment]
Still in progress of upgrade to support Phalcon 4.

**Comment by cgaugel** [comment]
IBAN Validator for Example

**Comment by hmfaysal** [comment]
Need Aerospike Cache

**Comment by colinberlinger** [comment]
I need Mvc/Model/EagerLoading for v4

**Comment by jenovateurs** [comment]
Hi @cgaugel,
I've just finished to migrate Incubator-validation to Phalcon v4.
You can find Iban Validator. Here is the repo: 
https://github.com/phalcon/incubator-validation

**Comment by Jeckerson** [comment]
> Hi @cgaugel,
> I've just finished to migrate Incubator-validation to Phalcon v4.
> You can find Iban Validator. Here is the repo:
> https://github.com/phalcon/incubator-validation

On packagist - https://packagist.org/packages/phalcon/incubator-validation

**Comment by Jeckerson** [comment]
Closing in favor: #911, #959
