### ISSUE TITLE
When i can use phalcon/incubator 4.0.5 in composer?

### ISSUE THREAD

**Issue by lovefields** [phalcon/incubator#943]
* Phalcon Framework version: 4.0.5
* Phalcon Incubator version: -
* PHP Version: 7.4.5
* Operating System: MAC / Ubuntu 16.04
* Server: Nginx

I'm making an my Docker Container.
And i using here code 'https://github.com/MilesChou/docker-phalcon/tree/master'.
So i make `composer.json` file and use command `composer install`.
But `phalcon/incubator` didn't not support `4.0.5`.
I tried to install another version but failed.
Only version 4.0.5 will be installed.

What can i do?

**Comment by Jeckerson** [comment]
What functionality you want from incubator? Currently there is upgrade process and queue list may vary, depending on community requests.

**Comment by lovefields** [comment]
Sorry, I saw the fix it downgrade.
