### ISSUE TITLE
UnitTests helper with Phalcon 4.0

### ISSUE THREAD

**Issue by zyuhel** [phalcon/incubator#945]
### Expected and Actual Behavior

When using UnitTestCase class from incubator it shows following error

```
PHP Fatal error:  Declaration of Phalcon\Test\PHPUnit\UnitTestCase::setDI(Phalcon\Test\PHPUnit\Phalcon\Di\DiInterface $container): void must be compatible with Phalcon\Di\InjectionAwareInterface::setDI(Phalcon\Di\DiInterface $container): void in
```

### Details

Reason of this error is changed namespace from Phalcon\DiInterface to Phalcon\Di\DiInterface and details of interface in Phalcon\Di\InjectionAwareInterface

* Phalcon Framework version: 4.0.2
* Phalcon Incubator version: composer v4.0.0-alpha.1
* PHP Version: PHP 7.2.24
* Operating System: Ubuntu
* Server: Other

**Comment by Jeckerson** [comment]
For Phalcon `v4` you have separate repository and composer package

* https://github.com/phalcon/incubator-test

**Comment by zyuhel** [comment]
Ok, thank you, so i will close issue and pr?

**Comment by Jeckerson** [comment]
Yes please
