### ISSUE TITLE
Phalcon\Session\Adapter classes upgrade

### ISSUE THREAD

**Issue by mikacalvo** [phalcon/incubator#948]
Following those guidelines https://docs.phalcon.io/4.0/en/session#custom, I listed those breaking changes :
- The namespace of extended class is wrong
- Methods : parent::_construct, isStarted, getId, getOptions (and property connection ?) belong to a Manager, not adapter
- Method open don't respect interface

I did my own adapter/manager in the meantime, hope you'll have time to implement the upgrade as we use your Database adapter in our app 🙏

**Comment by Jeckerson** [comment]
Work in progress

https://github.com/phalcon/incubator-session

**Comment by mikacalvo** [comment]
oh, such a good idea to use a side project for that. Didn't notice it. I'll test it tomorrow. Thank you for your response

**Comment by Jeckerson** [comment]
Released in `v4.0.0-alpha.2`

https://github.com/phalcon/incubator/releases/tag/v4.0.0-alpha.2

**Comment by mikacalvo** [comment]
`
$di->set('session', function () {
    // Create a connection
    $connection = new Mysql([
        'host'     => 'localhost',
        'username' => 'root',
        'password' => 'secret',
        'dbname'   => 'test',
    ]);

    $session = new Database($connection, 'session_data');
    $session->start();

    return $session;
});
`

I think you missed a doc update. It's still different from Phalcon guidelines, and the start method doesn't even exist.

If I'm not wrong, it should be : 

`
$di->set('session', function () {
    // Create a connection
    $connection = new Mysql([
        'host'     => 'localhost',
        'username' => 'root',
        'password' => 'secret',
        'dbname'   => 'test',
    ]);

    $session = new Database($connection, 'session_data');
    $session->start();

    $sessionManager = new \Phalcon\Session\Manager();
    $sessionManager->setAdapter(new Database(connection, 'session_data' ));
    $sessionManager->start();

    return $sessionManager;
});
`
