### ISSUE TITLE
ext-phalcon 4.0.5  composer install  phalcon/incubator error.

### ISSUE THREAD

**Issue by arlonlove** [phalcon/incubator#960]
- phalcon/incubator[v3.4.0, ..., v3.4.5] require ext-phalcon ~3.3 -> it has the wrong version (4.0.5) installed. Install or enable PHP's phalcon extension.
    - phalcon/incubator v3.4.6 requires ext-phalcon ^3.3 -> it has the wrong version (4.0.5) installed. Install or enable PHP's phalcon extension.

**Comment by Jeckerson** [comment]
Duplicate #911

You can use `alpha` version of `v4` or use specific incubator components inside your composer.json.
