### ISSUE TITLE
Uncaught Error: Class 'Phalcon\Mvc\Collection' not found 

### ISSUE THREAD

**Issue by ZMNOTZ** [phalcon/incubator#970]
> Questions should go to https://forum.phalconphp.com
> Documentation issues should go to https://github.com/phalcon/docs/issues

### Expected and Actual Behavior

> **Describe what you are trying to achieve and what goes wrong.**

> Provide output if related

```php
PHP Fatal error:  Uncaught Error: Class 'Phalcon\Mvc\Collection' not found in /Users/emery/Sites/localhost/server/vendor/phalcon/incubator/Library/Phalcon/Mvc/MongoCollection.php:39
Stack trace:
#0 /Users/emery/Sites/localhost/server/vendor/composer/ClassLoader.php(571): include()
#1 /Users/emery/Sites/localhost/server/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/emery/Si...')
#2 [internal function]: Composer\Autoload\ClassLoader->loadClass('Phalcon\\Mvc\\Mon...')
#3 /Users/emery/Sites/localhost/server/app/models/Favorites.php(6): spl_autoload_call('Phalcon\\Mvc\\Mon...')
#4 [internal function]: unknown()
#5 [internal function]: Phalcon\Loader->autoLoad('Favorites')
#6 /Users/emery/Sites/localhost/server/app/controllers/FrontapiController.php(758): spl_autoload_call('Favorites')
#7 [internal function]: FrontapiController->getMyFavoritesListAction()
#8 [internal function]: Phalcon\Dispatcher\AbstractDispatcher->callActionMethod(Object(FrontapiController), 'getMyFavoritesL...', Array)
#9 [internal  in /Users/emery/Sites/localhost/server/vendor/phalcon/incubator/Library/Phalcon/Mvc/MongoCollection.php on line 39

```
> Provide minimal script to reproduce the issue

```php
$favorite = new Favorites();//did not use namespace
$favorite->setType("article");
 $favorite->save();
```

### Details

* Phalcon Framework version: (`php --ri phalcon`)

  phalcon => enabled
  Author => Phalcon Team and contributors
  Version => 4.1.2
  Build Date => Oct  4 2021 21:24:23
  Powered by Zephir => Version 0.12.21-8a412a1
  
  Directive => Local Value => Master Value
  phalcon.db.escape_identifiers => On => On
  phalcon.db.force_casting => Off => Off
  phalcon.orm.case_insensitive_column_map => Off => Off
  phalcon.orm.cast_last_insert_id_to_int => Off => Off
  phalcon.orm.cast_on_hydrate => Off => Off
  phalcon.orm.column_renaming => On => On
  phalcon.orm.disable_assign_setters => Off => Off
  phalcon.orm.enable_implicit_joins => On => On
  phalcon.orm.enable_literals => On => On
  phalcon.orm.events => On => On
  phalcon.orm.exception_on_failed_save => Off => Off
  phalcon.orm.exception_on_failed_metadata_save => On => On
  phalcon.orm.ignore_unknown_columns => Off => Off
  phalcon.orm.late_state_binding => Off => Off
  phalcon.orm.not_null_validations => On => On
  phalcon.orm.update_snapshot_on_save => On => On
  phalcon.orm.virtual_foreign_keys => On => On
  phalcon.warning.enable => On => On

* Phalcon Incubator version: (branch, composer version)
"require": {
    "phalcon/incubator": "^3.4.0"
  }
* PHP Version: 7.3.29
* Operating System: MacOS 10.15.4
* Server: Apache
* Other related info: MngoDb & MAMP PRO intergration enviorment

**Comment by Jeckerson** [comment]
Try to use `phalcon/incubator-mongodb@v2.0.0`
