### ISSUE TITLE
Change out swiftmailer/swiftmailer for symphony/mailer

### ISSUE THREAD

**Issue by BradMcDev** [phalcon/incubator#972]
### Expected and Actual Behavior
**Expected:**
>  The mailer library used by the phalcon/incubator-mailer should be an active, updated package.

**Actual:**
> swiftmailer/swiftmailer is EOL / dead as of Nov 2021. Symphony now only supports their own mailer library, which is recommended to replace use of swiftmailer.

### Details

* Phalcon Framework version: All
* Phalcon Incubator version: incubator-mailer
* PHP Version: All
* Operating System: All
* Server: All

**Comment by borisdelev** [comment]
https://github.com/orgs/phalcon/discussions/16335
Yes, its moving to Symfony Mailer 😊

**Comment by Jeckerson** [comment]
Released in v2.0.0 (https://github.com/phalcon/incubator-mailer/releases/tag/v2.0.0)

**Comment by borisdelev** [comment]
> Released in v2.0.0 (https://github.com/phalcon/incubator-mailer/releases/tag/v2.0.0)

Thanks... just a question- is will work with Symfony Mailer (symfony/mailer)? I mean - can i use it?
