### ISSUE TITLE
incubator-mongodb implements Serializable which is deprecated in php8.1

### ISSUE THREAD

**Issue by noone-silent** [phalcon/incubator#975]
See https://www.php.net/manual/en/class.serializable It throws a lot of deprecation warnings

Solution:

1. Create version 3.0 for php8.1+
2. Remove interface `Serializable` and add `__serialize` and `__unserialize`

```php
    public function __serialize(): array
    {
        return $this->toArray();
    }

    public function __unserialize(array $data): void
    {
        $this->assign($data);
    }
```

Please note that `__serialize()` ha to return an `array` not `?string`!

**Comment by Jeckerson** [comment]
Fixed in `v2.0.1`
